export enum RuntimeStabilityState {
  POST_OPEN_VALIDATING = 'POST_OPEN_VALIDATING',
  STABLE_RUNTIME = 'STABLE_RUNTIME',
  DEGRADED_RUNTIME = 'DEGRADED_RUNTIME',
  RECOVERY_RUNTIME = 'RECOVERY_RUNTIME'
}
