-- Migration for clients (Part 1)

INSERT INTO clients (id, name, created_at, sales_total, loyalty_points, phone, email) VALUES ('22VpzrHvmb4FMwuRgTrK', 'Entreprise Alpha', '2026-04-27T12:30:04.837Z', 15400, 120, '01 23 45 67 89', 'contact@alpha.com') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, created_at = EXCLUDED.created_at, sales_total = EXCLUDED.sales_total, loyalty_points = EXCLUDED.loyalty_points, phone = EXCLUDED.phone, email = EXCLUDED.email;

INSERT INTO clients (id, address, phone, email, name, sales_total, loyalty_points, company_id, created_at) VALUES ('3A62iy8EamlMGoIa1nZj', 'Maroua', '694826986', 'feuhkumbac@gmail.com', 'Cyrille feuhku mba', 0, 0, '77KDhS2qYXrWrUaN35yD', '2026-05-08T09:58:54.187Z') ON CONFLICT (id) DO UPDATE SET address = EXCLUDED.address, phone = EXCLUDED.phone, email = EXCLUDED.email, name = EXCLUDED.name, sales_total = EXCLUDED.sales_total, loyalty_points = EXCLUDED.loyalty_points, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at;

INSERT INTO clients (id, name, address, email, phone, created_at, company_id, updated_at, loyalty_points, sales_total) VALUES ('L7zvj3iYVAZssKpafrCe', 'Raphael ', 'Maroua', 'raphaeldoba1@gmail.com', '656326890', '2026-05-08T09:43:53.611Z', '77KDhS2qYXrWrUaN35yD', '2026-05-08T14:39:35.422Z', 0, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, email = EXCLUDED.email, phone = EXCLUDED.phone, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, updated_at = EXCLUDED.updated_at, loyalty_points = EXCLUDED.loyalty_points, sales_total = EXCLUDED.sales_total;

INSERT INTO clients (id, name, created_at, sales_total, email, loyalty_points, phone) VALUES ('SXTTwj1ss0lFU2oWFgyr', 'Jean Martin', '2026-04-27T12:30:05.516Z', 3200, 'jean.martin@gmail.com', 45, '06 12 34 56 78') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, created_at = EXCLUDED.created_at, sales_total = EXCLUDED.sales_total, email = EXCLUDED.email, loyalty_points = EXCLUDED.loyalty_points, phone = EXCLUDED.phone;

INSERT INTO clients (id, sales_total, loyalty_points, updated_at, company_id, created_at, email, phone, address, name) VALUES ('UeCavY78ElTgHL2xA3WJ', 0, 0, '2026-05-08T14:39:28.841Z', '77KDhS2qYXrWrUaN35yD', '2026-05-08T13:32:03.497Z', 'doumaira52@gmail.com', '6570466603', 'Maroua ', 'DOUMARA') ON CONFLICT (id) DO UPDATE SET sales_total = EXCLUDED.sales_total, loyalty_points = EXCLUDED.loyalty_points, updated_at = EXCLUDED.updated_at, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, email = EXCLUDED.email, phone = EXCLUDED.phone, address = EXCLUDED.address, name = EXCLUDED.name;

INSERT INTO clients (id, created_at, company_id, loyalty_points, updated_at, sales_total, name, email, phone, address) VALUES ('alayeasna948@gmail.com', '2026-05-09T11:01:33.424Z', '77KDhS2qYXrWrUaN35yD', 0, '2026-05-09T11:01:33.424Z', 0, 'Alaye asna ', 'alayeasna948@gmail.com', '', 'Maroua') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, loyalty_points = EXCLUDED.loyalty_points, updated_at = EXCLUDED.updated_at, sales_total = EXCLUDED.sales_total, name = EXCLUDED.name, email = EXCLUDED.email, phone = EXCLUDED.phone, address = EXCLUDED.address;

INSERT INTO clients (id, company_id, created_at, sales_total, loyalty_points, updated_at, name, email, phone, address) VALUES ('bienvenudounia41@gmail.com', '77KDhS2qYXrWrUaN35yD', '2026-05-09T08:13:19.519Z', 0, 0, '2026-05-09T08:35:54.099Z', 'BIENVENUE ', 'bienvenudounia41@gmail.com', '691879186', 'Maroua') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, sales_total = EXCLUDED.sales_total, loyalty_points = EXCLUDED.loyalty_points, updated_at = EXCLUDED.updated_at, name = EXCLUDED.name, email = EXCLUDED.email, phone = EXCLUDED.phone, address = EXCLUDED.address;

INSERT INTO clients (id, sales_total, updated_at, loyalty_points, company_id, created_at, address, email, phone, name) VALUES ('lamisalberto@gmail.com', 0, '2026-05-10T10:31:10.047Z', 0, '77KDhS2qYXrWrUaN35yD', '2026-05-10T10:31:10.047Z', 'Maroua', 'lamisalberto@gmail.com', '696771132', 'Lamissia albert') ON CONFLICT (id) DO UPDATE SET sales_total = EXCLUDED.sales_total, updated_at = EXCLUDED.updated_at, loyalty_points = EXCLUDED.loyalty_points, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, address = EXCLUDED.address, email = EXCLUDED.email, phone = EXCLUDED.phone, name = EXCLUDED.name;
