-- Migration for stock_history (Part 1)

INSERT INTO stock_history (id, purchase_price, created_at, company_id, author_name, type, quantity, product_id, new_stock, reason, previous_stock, product_name) VALUES ('HsT5vJNy84mKdPRZKWV5', 0, '2026-06-13T14:38:25.049Z', 'ZHU4XkMEWWBgwfapUYPY', 'Admin', 'ENTREE', 1800, 'w9xRoMv1YojaDKFHu9ki', 2000, 'Mise à jour inventaire', 200, 'Spécial vacances utiles jeunes ') ON CONFLICT (id) DO UPDATE SET purchase_price = EXCLUDED.purchase_price, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, author_name = EXCLUDED.author_name, type = EXCLUDED.type, quantity = EXCLUDED.quantity, product_id = EXCLUDED.product_id, new_stock = EXCLUDED.new_stock, reason = EXCLUDED.reason, previous_stock = EXCLUDED.previous_stock, product_name = EXCLUDED.product_name;

INSERT INTO stock_history (id, product_name, previous_stock, product_id, new_stock, reason, author_name, type, quantity, created_at, purchase_price, company_id) VALUES ('RlxcesTviqkgUERVwESI', 'HP ELITE BOOK', 2, 'RpmtwpaUucdtsue2831g', 2, 'Mise à jour inventaire', 'Admin', 'SORTIE', 0, '2026-06-17T10:40:03.266Z', 0, 'T8FEwFdIPTqkepcYrMxK') ON CONFLICT (id) DO UPDATE SET product_name = EXCLUDED.product_name, previous_stock = EXCLUDED.previous_stock, product_id = EXCLUDED.product_id, new_stock = EXCLUDED.new_stock, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, type = EXCLUDED.type, quantity = EXCLUDED.quantity, created_at = EXCLUDED.created_at, purchase_price = EXCLUDED.purchase_price, company_id = EXCLUDED.company_id;

INSERT INTO stock_history (id, company_id, purchase_price, created_at, quantity, author_name, type, new_stock, reason, product_id, previous_stock, product_name) VALUES ('TdTj5MGnu63AC3Lpufj4', 'T8FEwFdIPTqkepcYrMxK', 0, '2026-06-03T11:44:54.375Z', 0, 'Admin', 'SORTIE', 15, 'Mise à jour inventaire', 'r46LfEn9KSKBKFv52EDL', 15, 'Ordinateur Portable Pro') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, purchase_price = EXCLUDED.purchase_price, created_at = EXCLUDED.created_at, quantity = EXCLUDED.quantity, author_name = EXCLUDED.author_name, type = EXCLUDED.type, new_stock = EXCLUDED.new_stock, reason = EXCLUDED.reason, product_id = EXCLUDED.product_id, previous_stock = EXCLUDED.previous_stock, product_name = EXCLUDED.product_name;

INSERT INTO stock_history (id, previous_stock, product_name, product_id, reason, new_stock, type, author_name, quantity, purchase_price, created_at, company_id) VALUES ('kmPCXpbLbebtVVRAAVAP', 15, 'Ordinateur Portable Pro', 'r46LfEn9KSKBKFv52EDL', 'Mise à jour inventaire', 15, 'SORTIE', 'Admin', 0, 0, '2026-06-03T11:45:21.348Z', 'T8FEwFdIPTqkepcYrMxK') ON CONFLICT (id) DO UPDATE SET previous_stock = EXCLUDED.previous_stock, product_name = EXCLUDED.product_name, product_id = EXCLUDED.product_id, reason = EXCLUDED.reason, new_stock = EXCLUDED.new_stock, type = EXCLUDED.type, author_name = EXCLUDED.author_name, quantity = EXCLUDED.quantity, purchase_price = EXCLUDED.purchase_price, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id;

INSERT INTO stock_history (id, previous_stock, product_name, new_stock, reason, product_id, quantity, author_name, type, company_id, purchase_price, created_at) VALUES ('qLqRGuUbgibY0UAdhRZF', 2, 'HP ELITE BOOK', 2, 'Mise à jour inventaire', 'RpmtwpaUucdtsue2831g', 0, 'Admin', 'SORTIE', 'T8FEwFdIPTqkepcYrMxK', 0, '2026-06-17T10:40:02.769Z') ON CONFLICT (id) DO UPDATE SET previous_stock = EXCLUDED.previous_stock, product_name = EXCLUDED.product_name, new_stock = EXCLUDED.new_stock, reason = EXCLUDED.reason, product_id = EXCLUDED.product_id, quantity = EXCLUDED.quantity, author_name = EXCLUDED.author_name, type = EXCLUDED.type, company_id = EXCLUDED.company_id, purchase_price = EXCLUDED.purchase_price, created_at = EXCLUDED.created_at;

INSERT INTO stock_history (id, purchase_price, created_at, company_id, author_name, type, quantity, product_id, new_stock, reason, previous_stock, product_name) VALUES ('vCxfRNiNaNMis8T9y0vE', 0, '2026-06-17T10:40:01.890Z', 'T8FEwFdIPTqkepcYrMxK', 'Admin', 'SORTIE', 0, 'RpmtwpaUucdtsue2831g', 2, 'Mise à jour inventaire', 2, 'HP ELITE BOOK') ON CONFLICT (id) DO UPDATE SET purchase_price = EXCLUDED.purchase_price, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, author_name = EXCLUDED.author_name, type = EXCLUDED.type, quantity = EXCLUDED.quantity, product_id = EXCLUDED.product_id, new_stock = EXCLUDED.new_stock, reason = EXCLUDED.reason, previous_stock = EXCLUDED.previous_stock, product_name = EXCLUDED.product_name;

INSERT INTO stock_history (id, purchase_price, created_at, company_id, type, author_name, quantity, product_id, reason, new_stock, previous_stock, product_name) VALUES ('xnCrIqIH5xWMni3R51C7', 0, '2026-06-19T06:28:41.354Z', '3XCUYDcYRkBTouVbHggE', 'SORTIE', 'Admin', 0, 'ptCvLJGCU5UYwiGfacsq', 'Mise à jour inventaire', 10, 10, ' Fer à repasser RAF ELECTRIC STEAM IRON') ON CONFLICT (id) DO UPDATE SET purchase_price = EXCLUDED.purchase_price, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, type = EXCLUDED.type, author_name = EXCLUDED.author_name, quantity = EXCLUDED.quantity, product_id = EXCLUDED.product_id, reason = EXCLUDED.reason, new_stock = EXCLUDED.new_stock, previous_stock = EXCLUDED.previous_stock, product_name = EXCLUDED.product_name;
