-- Migration for personnel (Part 1)

INSERT INTO personnel (id, email, tasks_assigned_count, created_at, company_id, last_name, role, status, department, name, phone, first_name, notes, updated_at) VALUES ('3XCUYDcYRkBTouVbHggE_ahmadouahmadou93@gmail.com', 'ahmadouahmadou93@gmail.com', 0, '2026-06-16T10:07:54.877Z', '3XCUYDcYRkBTouVbHggE', 'Mamoudou', 'Directeur', 'active', 'Général', 'Ahmadou Mamoudou', '699543847', 'Ahmadou', '', '2026-06-16T10:07:54.877Z') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, last_name = EXCLUDED.last_name, role = EXCLUDED.role, status = EXCLUDED.status, department = EXCLUDED.department, name = EXCLUDED.name, phone = EXCLUDED.phone, first_name = EXCLUDED.first_name, notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at;

INSERT INTO personnel (id, department, name, phone, first_name, updated_at, notes, email, created_at, tasks_assigned_count, last_name, company_id, role, status) VALUES ('3XCUYDcYRkBTouVbHggE_bbo27409@gmail.com', 'Général', 'Prosper DITCHING', '696251276', 'Prosper', '2026-06-19T13:01:57.872Z', '', 'bbo27409@gmail.com', '2026-06-19T13:01:57.872Z', 0, 'DITCHING ', '3XCUYDcYRkBTouVbHggE', 'Administrateur', 'active') ON CONFLICT (id) DO UPDATE SET department = EXCLUDED.department, name = EXCLUDED.name, phone = EXCLUDED.phone, first_name = EXCLUDED.first_name, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, email = EXCLUDED.email, created_at = EXCLUDED.created_at, tasks_assigned_count = EXCLUDED.tasks_assigned_count, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id, role = EXCLUDED.role, status = EXCLUDED.status;

INSERT INTO personnel (id, first_name, notes, updated_at, name, department, phone, last_name, company_id, created_at, tasks_assigned_count, status, role, email) VALUES ('3XCUYDcYRkBTouVbHggE_benamine798@gmail.com', 'AMINOU', '', '2026-06-16T09:22:18.016Z', 'AMINOU', 'Général', '695272061', '', '3XCUYDcYRkBTouVbHggE', '2026-06-16T09:22:18.016Z', 0, 'active', 'Administrateur', 'benamine798@gmail.com') ON CONFLICT (id) DO UPDATE SET first_name = EXCLUDED.first_name, notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at, name = EXCLUDED.name, department = EXCLUDED.department, phone = EXCLUDED.phone, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, tasks_assigned_count = EXCLUDED.tasks_assigned_count, status = EXCLUDED.status, role = EXCLUDED.role, email = EXCLUDED.email;

INSERT INTO personnel (id, created_at, company_id, updated_at, status, role, name, join_method, email, uid) VALUES ('3XCUYDcYRkBTouVbHggE_hackeurfaurest@gmail.com', '2026-06-16T09:19:23.949Z', '3XCUYDcYRkBTouVbHggE', '2026-06-16T09:19:23.949Z', 'active', 'owner', 'Faurest Hackeur', 'creation', 'hackeurfaurest@gmail.com', '1xW5bszECGO04Xv4zRWMqclvQmL2') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, updated_at = EXCLUDED.updated_at, status = EXCLUDED.status, role = EXCLUDED.role, name = EXCLUDED.name, join_method = EXCLUDED.join_method, email = EXCLUDED.email, uid = EXCLUDED.uid;

INSERT INTO personnel (id, notes, updated_at, first_name, phone, department, name, role, status, created_at, tasks_assigned_count, company_id, last_name, email) VALUES ('5KwQgwL8XrIJkokLit39', '', '2026-06-03T11:54:43.389Z', 'KOLLI ABE ', '', 'Général', 'KOLLI ABE  FLORENCE', 'Directeur', 'active', '2026-05-06T10:04:30.851Z', 0, '77KDhS2qYXrWrUaN35yD', 'FLORENCE ', 'florencekolliabe858@gmail.com') ON CONFLICT (id) DO UPDATE SET notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at, first_name = EXCLUDED.first_name, phone = EXCLUDED.phone, department = EXCLUDED.department, name = EXCLUDED.name, role = EXCLUDED.role, status = EXCLUDED.status, created_at = EXCLUDED.created_at, tasks_assigned_count = EXCLUDED.tasks_assigned_count, company_id = EXCLUDED.company_id, last_name = EXCLUDED.last_name, email = EXCLUDED.email;

INSERT INTO personnel (id, phone, department, name, notes, updated_at, first_name, email, role, status, created_at, tasks_assigned_count, last_name, company_id) VALUES ('77KDhS2qYXrWrUaN35yD_faurest@gmail.com', '', 'Général', 'FAUREST  Hackeur', '', '2026-06-04T19:16:36.757Z', 'FAUREST ', 'faurest@gmail.com', 'Collaborateur', 'active', '2026-06-02T11:56:37.821Z', 0, 'Hackeur ', '77KDhS2qYXrWrUaN35yD') ON CONFLICT (id) DO UPDATE SET phone = EXCLUDED.phone, department = EXCLUDED.department, name = EXCLUDED.name, notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at, first_name = EXCLUDED.first_name, email = EXCLUDED.email, role = EXCLUDED.role, status = EXCLUDED.status, created_at = EXCLUDED.created_at, tasks_assigned_count = EXCLUDED.tasks_assigned_count, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id;

INSERT INTO personnel (id, department, name, phone, first_name, updated_at, notes, email, created_at, tasks_assigned_count, last_name, company_id, status, role) VALUES ('GiH1v91ENaJLj4BHLMqq_fortunezebaze99@gmail.com', 'Général', 'Fortune Zebaze', '696278713', 'Fortune', '2026-06-16T08:37:48.884Z', '', 'fortunezebaze99@gmail.com', '2026-06-16T08:37:48.884Z', 0, 'Zebaze', 'GiH1v91ENaJLj4BHLMqq', 'active', 'Secrétaire') ON CONFLICT (id) DO UPDATE SET department = EXCLUDED.department, name = EXCLUDED.name, phone = EXCLUDED.phone, first_name = EXCLUDED.first_name, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, email = EXCLUDED.email, created_at = EXCLUDED.created_at, tasks_assigned_count = EXCLUDED.tasks_assigned_count, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id, status = EXCLUDED.status, role = EXCLUDED.role;

INSERT INTO personnel (id, uid, email, join_method, name, status, role, updated_at, company_id, created_at) VALUES ('GiH1v91ENaJLj4BHLMqq_hackeurfaurest@gmail.com', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'hackeurfaurest@gmail.com', 'creation', 'Faurest Hackeur', 'active', 'owner', '2026-06-16T08:23:52.584Z', 'GiH1v91ENaJLj4BHLMqq', '2026-06-16T08:23:52.584Z') ON CONFLICT (id) DO UPDATE SET uid = EXCLUDED.uid, email = EXCLUDED.email, join_method = EXCLUDED.join_method, name = EXCLUDED.name, status = EXCLUDED.status, role = EXCLUDED.role, updated_at = EXCLUDED.updated_at, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at;

INSERT INTO personnel (id, role, status, email, name, department, tasks_assigned_count, created_at) VALUES ('I6TAFYZjjgiZKc6q70tR', 'Responsable Ventes', 'active', 'alice.b@entreprise.com', 'Alice Bernard', 'Commercial', 3, '2026-04-27T12:30:10.065Z') ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role, status = EXCLUDED.status, email = EXCLUDED.email, name = EXCLUDED.name, department = EXCLUDED.department, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at;

INSERT INTO personnel (id, created_at, company_id, updated_at, role, status, join_method, name, uid, email) VALUES ('T8FEwFdIPTqkepcYrMxK_hackeurfaurest@gmail.com', '2026-06-05T06:54:51.979Z', 'T8FEwFdIPTqkepcYrMxK', '2026-06-05T06:54:51.979Z', 'owner', 'active', 'auto_sync', 'Faurest Hackeur', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'hackeurfaurest@gmail.com') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, updated_at = EXCLUDED.updated_at, role = EXCLUDED.role, status = EXCLUDED.status, join_method = EXCLUDED.join_method, name = EXCLUDED.name, uid = EXCLUDED.uid, email = EXCLUDED.email;

INSERT INTO personnel (id, notes, updated_at, first_name, phone, name, department, status, role, last_name, company_id, tasks_assigned_count, created_at, email) VALUES ('T8FEwFdIPTqkepcYrMxK_zakariyaouabdou004@gmail.com', '', '2026-06-17T09:51:42.040Z', 'ZAKARIYAOU', '697313427', 'ZAKARIYAOU Abdoulaye', 'Général', 'active', 'Administrateur', 'Abdoulaye ', 'T8FEwFdIPTqkepcYrMxK', 0, '2026-06-17T09:49:20.776Z', 'zakariyaouabdou004@gmail.com') ON CONFLICT (id) DO UPDATE SET notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at, first_name = EXCLUDED.first_name, phone = EXCLUDED.phone, name = EXCLUDED.name, department = EXCLUDED.department, status = EXCLUDED.status, role = EXCLUDED.role, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at, email = EXCLUDED.email;

INSERT INTO personnel (id, company_id, created_at, role, status, updated_at, name, join_method, email, uid) VALUES ('ZHU4XkMEWWBgwfapUYPY_hackeurfaurest@gmail.com', 'ZHU4XkMEWWBgwfapUYPY', '2026-06-09T09:20:53.405Z', 'owner', 'active', '2026-06-09T09:20:53.405Z', 'Faurest Hackeur', 'creation', 'hackeurfaurest@gmail.com', '1xW5bszECGO04Xv4zRWMqclvQmL2') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, role = EXCLUDED.role, status = EXCLUDED.status, updated_at = EXCLUDED.updated_at, name = EXCLUDED.name, join_method = EXCLUDED.join_method, email = EXCLUDED.email, uid = EXCLUDED.uid;

INSERT INTO personnel (id, phone, department, name, updated_at, notes, first_name, email, status, role, created_at, tasks_assigned_count, last_name, company_id) VALUES ('ZHU4XkMEWWBgwfapUYPY_mohamadoulamobabila@gmail.com', '692221608', 'Général', 'Babila Mohamadou lamo', '2026-06-09T09:23:28.270Z', '', 'Babila', 'mohamadoulamobabila@gmail.com', 'active', 'Directeur', '2026-06-09T09:23:28.270Z', 0, 'Mohamadou lamo', 'ZHU4XkMEWWBgwfapUYPY') ON CONFLICT (id) DO UPDATE SET phone = EXCLUDED.phone, department = EXCLUDED.department, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, first_name = EXCLUDED.first_name, email = EXCLUDED.email, status = EXCLUDED.status, role = EXCLUDED.role, created_at = EXCLUDED.created_at, tasks_assigned_count = EXCLUDED.tasks_assigned_count, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id;

INSERT INTO personnel (id, email, status, role, last_name, company_id, tasks_assigned_count, created_at, phone, name, department, updated_at, notes, first_name) VALUES ('hammadoud230@gmail.com', 'hammadoud230@gmail.com', 'active', 'Personnel', 'MAN EGRE ', '77KDhS2qYXrWrUaN35yD', 0, '2026-05-17T09:38:08.394Z', '', 'HAMMADOU  MAN EGRE', 'Général', '2026-05-17T09:38:08.394Z', '', 'HAMMADOU ') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, status = EXCLUDED.status, role = EXCLUDED.role, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at, phone = EXCLUDED.phone, name = EXCLUDED.name, department = EXCLUDED.department, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, first_name = EXCLUDED.first_name;

INSERT INTO personnel (id, email, role, status, created_at, tasks_assigned_count, department, name) VALUES ('loL5uL4o7BnDUw5tjHms', 'bob.r@entreprise.com', 'Directeur Logistique', 'active', '2026-04-27T12:30:10.520Z', 12, 'Opérations', 'Bob Richards') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, role = EXCLUDED.role, status = EXCLUDED.status, created_at = EXCLUDED.created_at, tasks_assigned_count = EXCLUDED.tasks_assigned_count, department = EXCLUDED.department, name = EXCLUDED.name;

INSERT INTO personnel (id, role, status, tasks_assigned_count, created_at, last_name, company_id, email, notes, updated_at, first_name, phone, department, name) VALUES ('ulXfHCA3QvbrCb0c4oXm', 'Directeur', 'active', 0, '2026-05-27T06:59:56.743Z', 'FLORENCE ', '77KDhS2qYXrWrUaN35yD', 'yaoubaboubakary43@gmail.com', '', '2026-05-06T13:24:23.054Z', 'KOLLI ABE ', '', 'Général', '(Clone) KOLLI ABE  FLORENCE') ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role, status = EXCLUDED.status, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id, email = EXCLUDED.email, notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at, first_name = EXCLUDED.first_name, phone = EXCLUDED.phone, department = EXCLUDED.department, name = EXCLUDED.name;

INSERT INTO personnel (id, first_name, updated_at, notes, name, department, phone, last_name, company_id, tasks_assigned_count, created_at, role, status, email) VALUES ('yaoubaboubakary43@gmail.com', 'BOUBAKARY ', '2026-05-27T06:56:41.881Z', '', 'BOUBAKARY  Yaouba', 'Général', '', 'Yaouba ', 'T8FEwFdIPTqkepcYrMxK', 0, '2026-05-16T18:07:52.423Z', 'Directeur', 'active', 'yaoubaboubakary43@gmail.com') ON CONFLICT (id) DO UPDATE SET first_name = EXCLUDED.first_name, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, name = EXCLUDED.name, department = EXCLUDED.department, phone = EXCLUDED.phone, last_name = EXCLUDED.last_name, company_id = EXCLUDED.company_id, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at, role = EXCLUDED.role, status = EXCLUDED.status, email = EXCLUDED.email;
