-- Migration for notifications (Part 1)

INSERT INTO notifications (id, message, date, is_read, title, updated_at, type, created_at, user_id, company_id) VALUES ('6OA85eiQb4rQnRECXrWO', 'Adamou a passé une commande de 10 500 FCFA. Paiement: Espèces.', '2026-05-14T10:50:57.303Z', 1, 'Nouvelle Commande (Cash sur place)', '2026-05-18T07:50:12.679Z', 'alert', '2026-05-14T10:50:57.303Z', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '77KDhS2qYXrWrUaN35yD') ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, date = EXCLUDED.date, is_read = EXCLUDED.is_read, title = EXCLUDED.title, updated_at = EXCLUDED.updated_at, type = EXCLUDED.type, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id;

INSERT INTO notifications (id, user_id, company_id, created_at, type, updated_at, title, is_read, message, date) VALUES ('7X2MepDaqTlf4AIGMmup', '1xW5bszECGO04Xv4zRWMqclvQmL2', '3XCUYDcYRkBTouVbHggE', '2026-06-16T17:06:04.169Z', 'alert', '2026-06-17T08:01:42.036Z', 'Nouvelle Commande (Cash sur place)', 1, 'Faurest a passé une commande de 13 000 FCFA. Paiement: Espèces.', '2026-06-16T17:06:04.169Z') ON CONFLICT (id) DO UPDATE SET user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, title = EXCLUDED.title, is_read = EXCLUDED.is_read, message = EXCLUDED.message, date = EXCLUDED.date;

INSERT INTO notifications (id, created_at, is_read, company_id, user_id, title, date, message, type) VALUES ('7eznEJtvnlZUXDBWRWRA', '2026-06-05T09:29:13.268Z', 0, '77KDhS2qYXrWrUaN35yD', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', 'Nouvelle Commande (Cash sur place)', '2026-06-05T09:29:13.268Z', 'FAUREST  a passé une commande de 650 FCFA. Paiement: Espèces.', 'alert') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, is_read = EXCLUDED.is_read, company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id, title = EXCLUDED.title, date = EXCLUDED.date, message = EXCLUDED.message, type = EXCLUDED.type;

INSERT INTO notifications (id, user_id, company_id, created_at, type, updated_at, title, is_read, message, date) VALUES ('AS3idHaVx2gEGj322TyL', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'comp_nexus_master', '2026-06-15T12:28:46.962Z', 'alert', '2026-06-16T13:57:21.473Z', 'Nouvelle Commande (Cash sur place)', 1, 'faurest a passé une commande de 10 000 FCFA. Paiement: Espèces.', '2026-06-15T12:28:46.962Z') ON CONFLICT (id) DO UPDATE SET user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, title = EXCLUDED.title, is_read = EXCLUDED.is_read, message = EXCLUDED.message, date = EXCLUDED.date;

INSERT INTO notifications (id, date, message, title, is_read, updated_at, type, user_id, company_id, created_at) VALUES ('DE04FhKfEG2daOrtQ6Ze', '2026-05-12T11:19:28.981Z', 'Faurest  a passé une commande de 1 260 500 FCFA. Paiement: Espèces.', 'Nouvelle Commande (Cash sur place)', 1, '2026-05-18T07:50:13.434Z', 'alert', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '77KDhS2qYXrWrUaN35yD', '2026-05-12T11:19:28.981Z') ON CONFLICT (id) DO UPDATE SET date = EXCLUDED.date, message = EXCLUDED.message, title = EXCLUDED.title, is_read = EXCLUDED.is_read, updated_at = EXCLUDED.updated_at, type = EXCLUDED.type, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at;

INSERT INTO notifications (id, company_id, user_id, title, created_at, is_read, message, date, type) VALUES ('DMJt06Wo7iXxbUYVpJ0N', '77KDhS2qYXrWrUaN35yD', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', 'Nouvelle Commande (Cash sur place)', '2026-06-12T12:39:22.429Z', 0, 'Faurest a passé une commande de 9 000 FCFA. Paiement: Espèces.', '2026-06-12T12:39:22.429Z', 'alert') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id, title = EXCLUDED.title, created_at = EXCLUDED.created_at, is_read = EXCLUDED.is_read, message = EXCLUDED.message, date = EXCLUDED.date, type = EXCLUDED.type;

INSERT INTO notifications (id, date, message, is_read, title, type, updated_at, created_at, company_id, user_id) VALUES ('E0brjhmwxTmmB0VrnKSz', 1778089409412, 'Le niveau de stock pour "RAM DE FORMAT" est faible (2 restants).', 1, 'Alerte de Stock Faible', 'alert', '2026-05-07T09:24:18.730Z', '2026-05-06T17:43:30.665Z', '77KDhS2qYXrWrUaN35yD', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63') ON CONFLICT (id) DO UPDATE SET date = EXCLUDED.date, message = EXCLUDED.message, is_read = EXCLUDED.is_read, title = EXCLUDED.title, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id;

INSERT INTO notifications (id, message, date, type, created_at, is_read, company_id, user_id, title) VALUES ('ETa4z1UMt1m86F6FK0TJ', 'Félicité Danga vous a envoyé un message.', 1778141450663, 'general', '2026-05-07T08:10:51.763Z', 0, '77KDhS2qYXrWrUaN35yD', '5KwQgwL8XrIJkokLit39', 'Nouveau message direct') ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, date = EXCLUDED.date, type = EXCLUDED.type, created_at = EXCLUDED.created_at, is_read = EXCLUDED.is_read, company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id, title = EXCLUDED.title;

INSERT INTO notifications (id, is_read, title, date, message, created_at, user_id, company_id, updated_at, type) VALUES ('EhwHrJ5lhg7X1puqutBu', 1, 'Nouvelle Commande (Cash sur place)', '2026-06-16T17:09:09.034Z', 'Faurest a passé une commande de 1 500 FCFA. Paiement: Espèces.', '2026-06-16T17:09:09.034Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', '3XCUYDcYRkBTouVbHggE', '2026-06-17T08:00:46.232Z', 'alert') ON CONFLICT (id) DO UPDATE SET is_read = EXCLUDED.is_read, title = EXCLUDED.title, date = EXCLUDED.date, message = EXCLUDED.message, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, updated_at = EXCLUDED.updated_at, type = EXCLUDED.type;

INSERT INTO notifications (id, date, message, is_read, title, type, updated_at, created_at, company_id, user_id) VALUES ('FSUxiySpUxXVh2E5op8p', '2026-05-11T21:38:20.555Z', 'Le bolc a passé une commande de 10 650 FCFA et a payé par ORANGE.', 1, 'URGENT: Nouvelle Commande Marketplace Payée !', 'alert', '2026-05-18T07:51:31.304Z', '2026-05-11T21:38:20.555Z', '77KDhS2qYXrWrUaN35yD', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63') ON CONFLICT (id) DO UPDATE SET date = EXCLUDED.date, message = EXCLUDED.message, is_read = EXCLUDED.is_read, title = EXCLUDED.title, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id;

INSERT INTO notifications (id, type, updated_at, user_id, company_id, created_at, date, message, title, is_read) VALUES ('PKEQ9Dg39sVelWrpphGx', 'alert', '2026-05-12T12:14:06.872Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'comp_nexus_master', '2026-05-11T21:56:54.398Z', '2026-05-11T21:56:54.398Z', 'Lord a passé une commande de 1 250 000 FCFA. Paiement: UNKNOWN.', 'Commande Marketplace Payée !', 1) ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, date = EXCLUDED.date, message = EXCLUDED.message, title = EXCLUDED.title, is_read = EXCLUDED.is_read;

INSERT INTO notifications (id, company_id, user_id, created_at, type, updated_at, title, is_read, date, message) VALUES ('RoTcjLrt4aTfJeQ5Dlwu', 'ZHU4XkMEWWBgwfapUYPY', '1xW5bszECGO04Xv4zRWMqclvQmL2', '2026-06-15T12:28:48.086Z', 'alert', '2026-06-15T12:32:28.635Z', 'Nouvelle Commande (Cash sur place)', 1, '2026-06-15T12:28:48.086Z', 'faurest a passé une commande de 15 000 FCFA. Paiement: Espèces.') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id, created_at = EXCLUDED.created_at, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, title = EXCLUDED.title, is_read = EXCLUDED.is_read, date = EXCLUDED.date, message = EXCLUDED.message;

INSERT INTO notifications (id, updated_at, type, created_at, user_id, company_id, message, date, is_read, title) VALUES ('TbrkshTrQMP8bM9ZknlA', '2026-06-18T10:24:10.744Z', 'alert', '2026-06-17T11:03:26.258Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', '3XCUYDcYRkBTouVbHggE', 'Pro a passé une commande de 2 500 FCFA. Paiement: Espèces.', '2026-06-17T11:03:26.258Z', 1, 'Nouvelle Commande (Cash sur place)') ON CONFLICT (id) DO UPDATE SET updated_at = EXCLUDED.updated_at, type = EXCLUDED.type, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, message = EXCLUDED.message, date = EXCLUDED.date, is_read = EXCLUDED.is_read, title = EXCLUDED.title;

INSERT INTO notifications (id, message, date, is_read, title, type, updated_at, created_at, user_id, company_id) VALUES ('Z7dYwSLy6x4DhDCjE8QU', 'Faurest a passé une commande de 10 000 FCFA. Paiement: Espèces.', '2026-06-22T14:37:01.567Z', 1, 'Nouvelle Commande (Cash sur place)', 'alert', '2026-06-22T14:37:42.472Z', '2026-06-22T14:37:01.567Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'comp_nexus_master') ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, date = EXCLUDED.date, is_read = EXCLUDED.is_read, title = EXCLUDED.title, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id;

INSERT INTO notifications (id, updated_at, type, created_at, user_id, company_id, message, date, is_read, title) VALUES ('jNgaIAObN1C9TknkFUZo', '2026-05-07T09:24:06.633Z', 'alert', '2026-05-06T17:44:01.234Z', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '77KDhS2qYXrWrUaN35yD', 'Le niveau de stock pour "RAM DE FORMAT" est faible (2 restants).', 1778089439962, 1, 'Alerte de Stock Faible') ON CONFLICT (id) DO UPDATE SET updated_at = EXCLUDED.updated_at, type = EXCLUDED.type, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, message = EXCLUDED.message, date = EXCLUDED.date, is_read = EXCLUDED.is_read, title = EXCLUDED.title;

INSERT INTO notifications (id, type, updated_at, created_at, company_id, user_id, date, message, is_read, title) VALUES ('l2PaJ5HBUjtvlgfIC1uA', 'alert', '2026-05-18T07:50:54.116Z', '2026-05-11T21:56:51.997Z', '77KDhS2qYXrWrUaN35yD', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '2026-05-11T21:56:51.997Z', 'Lord a passé une commande de 5 150 FCFA. Paiement: UNKNOWN.', 1, 'Commande Marketplace Payée !') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id, date = EXCLUDED.date, message = EXCLUDED.message, is_read = EXCLUDED.is_read, title = EXCLUDED.title;

INSERT INTO notifications (id, company_id, user_id, created_at, type, updated_at, title, is_read, date, message) VALUES ('lA2M1TOOy0PlUYgE69W8', '77KDhS2qYXrWrUaN35yD', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '2026-05-06T17:36:36.757Z', 'alert', '2026-05-07T09:25:15.277Z', 'Alerte de Stock Faible', 1, 1778088995530, 'Le niveau de stock pour "RAM DE FORMAT" est faible (5 restants).') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id, created_at = EXCLUDED.created_at, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, title = EXCLUDED.title, is_read = EXCLUDED.is_read, date = EXCLUDED.date, message = EXCLUDED.message;

INSERT INTO notifications (id, date, message, is_read, title, type, updated_at, created_at, user_id, company_id) VALUES ('laI1N4EuSWId33Gwiacg', '2026-06-09T10:07:37.830Z', 'Félicité Danga vous a envoyé un message.', 1, 'Nouveau message direct', 'general', '2026-06-09T10:32:10.853Z', '2026-06-09T10:07:37.830Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'ZHU4XkMEWWBgwfapUYPY') ON CONFLICT (id) DO UPDATE SET date = EXCLUDED.date, message = EXCLUDED.message, is_read = EXCLUDED.is_read, title = EXCLUDED.title, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id;

INSERT INTO notifications (id, date, message, is_read, title, type, updated_at, created_at, user_id, company_id) VALUES ('vov82ci29HUNwC6KK7iV', '2026-06-19T13:20:30.630Z', 'Un collègue vous a envoyé un message.', 1, 'Nouveau message direct', 'general', '2026-06-22T08:20:30.056Z', '2026-06-19T13:20:30.630Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', '3XCUYDcYRkBTouVbHggE') ON CONFLICT (id) DO UPDATE SET date = EXCLUDED.date, message = EXCLUDED.message, is_read = EXCLUDED.is_read, title = EXCLUDED.title, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id;
