-- Migration for personnel (Part 1)

INSERT INTO personnel (id, last_name, department, company_id, name, tasks_assigned_count, first_name, status, created_at, role, email, phone, updated_at, notes) VALUES ('3XCUYDcYRkBTouVbHggE_ahmadouahmadou93@gmail.com', 'Mamoudou', 'Général', '3XCUYDcYRkBTouVbHggE', 'Ahmadou Mamoudou', 0, 'Ahmadou', 'active', '2026-06-16T10:07:54.877Z', 'Directeur', 'ahmadouahmadou93@gmail.com', '699543847', '2026-06-16T10:07:54.877Z', '') ON CONFLICT (id) DO UPDATE SET last_name = EXCLUDED.last_name, department = EXCLUDED.department, company_id = EXCLUDED.company_id, name = EXCLUDED.name, tasks_assigned_count = EXCLUDED.tasks_assigned_count, first_name = EXCLUDED.first_name, status = EXCLUDED.status, created_at = EXCLUDED.created_at, role = EXCLUDED.role, email = EXCLUDED.email, phone = EXCLUDED.phone, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes;

INSERT INTO personnel (id, created_at, status, first_name, tasks_assigned_count, name, company_id, department, last_name, updated_at, notes, phone, email, role) VALUES ('3XCUYDcYRkBTouVbHggE_bbo27409@gmail.com', '2026-06-19T13:01:57.872Z', 'active', 'Prosper', 0, 'Prosper DITCHING', '3XCUYDcYRkBTouVbHggE', 'Général', 'DITCHING ', '2026-06-19T13:01:57.872Z', '', '696251276', 'bbo27409@gmail.com', 'Administrateur') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, status = EXCLUDED.status, first_name = EXCLUDED.first_name, tasks_assigned_count = EXCLUDED.tasks_assigned_count, name = EXCLUDED.name, company_id = EXCLUDED.company_id, department = EXCLUDED.department, last_name = EXCLUDED.last_name, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, phone = EXCLUDED.phone, email = EXCLUDED.email, role = EXCLUDED.role;

INSERT INTO personnel (id, updated_at, notes, phone, email, role, created_at, tasks_assigned_count, first_name, status, company_id, name, last_name, department) VALUES ('3XCUYDcYRkBTouVbHggE_benamine798@gmail.com', '2026-06-16T09:22:18.016Z', '', '695272061', 'benamine798@gmail.com', 'Administrateur', '2026-06-16T09:22:18.016Z', 0, 'AMINOU', 'active', '3XCUYDcYRkBTouVbHggE', 'AMINOU', '', 'Général') ON CONFLICT (id) DO UPDATE SET updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, phone = EXCLUDED.phone, email = EXCLUDED.email, role = EXCLUDED.role, created_at = EXCLUDED.created_at, tasks_assigned_count = EXCLUDED.tasks_assigned_count, first_name = EXCLUDED.first_name, status = EXCLUDED.status, company_id = EXCLUDED.company_id, name = EXCLUDED.name, last_name = EXCLUDED.last_name, department = EXCLUDED.department;

INSERT INTO personnel (id, status, updated_at, created_at, join_method, role, name, uid, email, company_id) VALUES ('3XCUYDcYRkBTouVbHggE_hackeurfaurest@gmail.com', 'active', '2026-06-16T09:19:23.949Z', '2026-06-16T09:19:23.949Z', 'creation', 'owner', 'Faurest Hackeur', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'hackeurfaurest@gmail.com', '3XCUYDcYRkBTouVbHggE') ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, join_method = EXCLUDED.join_method, role = EXCLUDED.role, name = EXCLUDED.name, uid = EXCLUDED.uid, email = EXCLUDED.email, company_id = EXCLUDED.company_id;

INSERT INTO personnel (id, created_at, first_name, status, tasks_assigned_count, company_id, name, last_name, department, updated_at, notes, phone, email, role) VALUES ('5KwQgwL8XrIJkokLit39', '2026-05-06T10:04:30.851Z', 'KOLLI ABE ', 'active', 0, '77KDhS2qYXrWrUaN35yD', 'KOLLI ABE  FLORENCE', 'FLORENCE ', 'Général', '2026-06-03T11:54:43.389Z', '', '', 'florencekolliabe858@gmail.com', 'Directeur') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, first_name = EXCLUDED.first_name, status = EXCLUDED.status, tasks_assigned_count = EXCLUDED.tasks_assigned_count, company_id = EXCLUDED.company_id, name = EXCLUDED.name, last_name = EXCLUDED.last_name, department = EXCLUDED.department, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, phone = EXCLUDED.phone, email = EXCLUDED.email, role = EXCLUDED.role;

INSERT INTO personnel (id, last_name, department, company_id, name, status, first_name, tasks_assigned_count, created_at, role, email, phone, updated_at, notes) VALUES ('77KDhS2qYXrWrUaN35yD_faurest@gmail.com', 'Hackeur ', 'Général', '77KDhS2qYXrWrUaN35yD', 'FAUREST  Hackeur', 'active', 'FAUREST ', 0, '2026-06-02T11:56:37.821Z', 'Collaborateur', 'faurest@gmail.com', '', '2026-06-04T19:16:36.757Z', '') ON CONFLICT (id) DO UPDATE SET last_name = EXCLUDED.last_name, department = EXCLUDED.department, company_id = EXCLUDED.company_id, name = EXCLUDED.name, status = EXCLUDED.status, first_name = EXCLUDED.first_name, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at, role = EXCLUDED.role, email = EXCLUDED.email, phone = EXCLUDED.phone, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes;

INSERT INTO personnel (id, phone, notes, updated_at, role, email, status, first_name, tasks_assigned_count, created_at, department, last_name, name, company_id) VALUES ('GiH1v91ENaJLj4BHLMqq_fortunezebaze99@gmail.com', '696278713', '', '2026-06-16T08:37:48.884Z', 'Secrétaire', 'fortunezebaze99@gmail.com', 'active', 'Fortune', 0, '2026-06-16T08:37:48.884Z', 'Général', 'Zebaze', 'Fortune Zebaze', 'GiH1v91ENaJLj4BHLMqq') ON CONFLICT (id) DO UPDATE SET phone = EXCLUDED.phone, notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at, role = EXCLUDED.role, email = EXCLUDED.email, status = EXCLUDED.status, first_name = EXCLUDED.first_name, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at, department = EXCLUDED.department, last_name = EXCLUDED.last_name, name = EXCLUDED.name, company_id = EXCLUDED.company_id;

INSERT INTO personnel (id, status, join_method, updated_at, created_at, role, email, uid, name, company_id) VALUES ('GiH1v91ENaJLj4BHLMqq_hackeurfaurest@gmail.com', 'active', 'creation', '2026-06-16T08:23:52.584Z', '2026-06-16T08:23:52.584Z', 'owner', 'hackeurfaurest@gmail.com', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'Faurest Hackeur', 'GiH1v91ENaJLj4BHLMqq') ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, join_method = EXCLUDED.join_method, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, role = EXCLUDED.role, email = EXCLUDED.email, uid = EXCLUDED.uid, name = EXCLUDED.name, company_id = EXCLUDED.company_id;

INSERT INTO personnel (id, department, status, role, tasks_assigned_count, name, email, created_at) VALUES ('I6TAFYZjjgiZKc6q70tR', 'Commercial', 'active', 'Responsable Ventes', 3, 'Alice Bernard', 'alice.b@entreprise.com', '2026-04-27T12:30:10.065Z') ON CONFLICT (id) DO UPDATE SET department = EXCLUDED.department, status = EXCLUDED.status, role = EXCLUDED.role, tasks_assigned_count = EXCLUDED.tasks_assigned_count, name = EXCLUDED.name, email = EXCLUDED.email, created_at = EXCLUDED.created_at;

INSERT INTO personnel (id, department, tasks_assigned_count, role, status, email, name, created_at, company_id) VALUES ('MLgMuZSPhGleemwJWNMY', 'Général', 0, 'Collaborateur', 'active', 'yaoubaboubakary43@gmail.com', '(Clone) Florence', '2026-05-27T06:59:58.112Z', 'KkjpgY9uaERRPC5qrlZq') ON CONFLICT (id) DO UPDATE SET department = EXCLUDED.department, tasks_assigned_count = EXCLUDED.tasks_assigned_count, role = EXCLUDED.role, status = EXCLUDED.status, email = EXCLUDED.email, name = EXCLUDED.name, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id;

INSERT INTO personnel (id, email, name, company_id, department, tasks_assigned_count, role, status) VALUES ('PMFYinDhui8edokgf5wH', 'florencekolliabe858@gmail.com', 'Florence ', 'KkjpgY9uaERRPC5qrlZq', 'Général', 0, 'Collaborateur', 'active') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, company_id = EXCLUDED.company_id, department = EXCLUDED.department, tasks_assigned_count = EXCLUDED.tasks_assigned_count, role = EXCLUDED.role, status = EXCLUDED.status;

INSERT INTO personnel (id, company_id, name, email, uid, role, updated_at, created_at, join_method, status) VALUES ('T8FEwFdIPTqkepcYrMxK_hackeurfaurest@gmail.com', 'T8FEwFdIPTqkepcYrMxK', 'Faurest Hackeur', 'hackeurfaurest@gmail.com', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'owner', '2026-06-05T06:54:51.979Z', '2026-06-05T06:54:51.979Z', 'auto_sync', 'active') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, name = EXCLUDED.name, email = EXCLUDED.email, uid = EXCLUDED.uid, role = EXCLUDED.role, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, join_method = EXCLUDED.join_method, status = EXCLUDED.status;

INSERT INTO personnel (id, email, role, updated_at, notes, phone, name, company_id, department, last_name, created_at, first_name, status, tasks_assigned_count) VALUES ('T8FEwFdIPTqkepcYrMxK_zakariyaouabdou004@gmail.com', 'zakariyaouabdou004@gmail.com', 'Administrateur', '2026-06-17T09:51:42.040Z', '', '697313427', 'ZAKARIYAOU Abdoulaye', 'T8FEwFdIPTqkepcYrMxK', 'Général', 'Abdoulaye ', '2026-06-17T09:49:20.776Z', 'ZAKARIYAOU', 'active', 0) ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, role = EXCLUDED.role, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, phone = EXCLUDED.phone, name = EXCLUDED.name, company_id = EXCLUDED.company_id, department = EXCLUDED.department, last_name = EXCLUDED.last_name, created_at = EXCLUDED.created_at, first_name = EXCLUDED.first_name, status = EXCLUDED.status, tasks_assigned_count = EXCLUDED.tasks_assigned_count;

INSERT INTO personnel (id, role, company_id, email, uid, name, status, join_method, updated_at, created_at) VALUES ('ZHU4XkMEWWBgwfapUYPY_hackeurfaurest@gmail.com', 'owner', 'ZHU4XkMEWWBgwfapUYPY', 'hackeurfaurest@gmail.com', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'Faurest Hackeur', 'active', 'creation', '2026-06-09T09:20:53.405Z', '2026-06-09T09:20:53.405Z') ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role, company_id = EXCLUDED.company_id, email = EXCLUDED.email, uid = EXCLUDED.uid, name = EXCLUDED.name, status = EXCLUDED.status, join_method = EXCLUDED.join_method, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at;

INSERT INTO personnel (id, email, role, updated_at, notes, phone, company_id, name, last_name, department, created_at, first_name, status, tasks_assigned_count) VALUES ('ZHU4XkMEWWBgwfapUYPY_mohamadoulamobabila@gmail.com', 'mohamadoulamobabila@gmail.com', 'Directeur', '2026-06-09T09:23:28.270Z', '', '692221608', 'ZHU4XkMEWWBgwfapUYPY', 'Babila Mohamadou lamo', 'Mohamadou lamo', 'Général', '2026-06-09T09:23:28.270Z', 'Babila', 'active', 0) ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, role = EXCLUDED.role, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, phone = EXCLUDED.phone, company_id = EXCLUDED.company_id, name = EXCLUDED.name, last_name = EXCLUDED.last_name, department = EXCLUDED.department, created_at = EXCLUDED.created_at, first_name = EXCLUDED.first_name, status = EXCLUDED.status, tasks_assigned_count = EXCLUDED.tasks_assigned_count;

INSERT INTO personnel (id, email, name, company_id, department, tasks_assigned_count, status, role) VALUES ('cZNuMUDddg46vLdeLXos', 'dine@gmail.com', 'Dine', 'KkjpgY9uaERRPC5qrlZq', 'Général', 0, 'active', 'Collaborateur') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name, company_id = EXCLUDED.company_id, department = EXCLUDED.department, tasks_assigned_count = EXCLUDED.tasks_assigned_count, status = EXCLUDED.status, role = EXCLUDED.role;

INSERT INTO personnel (id, email, role, updated_at, notes, phone, company_id, name, last_name, department, created_at, first_name, status, tasks_assigned_count) VALUES ('hammadoud230@gmail.com', 'hammadoud230@gmail.com', 'Personnel', '2026-05-17T09:38:08.394Z', '', '', '77KDhS2qYXrWrUaN35yD', 'HAMMADOU  MAN EGRE', 'MAN EGRE ', 'Général', '2026-05-17T09:38:08.394Z', 'HAMMADOU ', 'active', 0) ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, role = EXCLUDED.role, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, phone = EXCLUDED.phone, company_id = EXCLUDED.company_id, name = EXCLUDED.name, last_name = EXCLUDED.last_name, department = EXCLUDED.department, created_at = EXCLUDED.created_at, first_name = EXCLUDED.first_name, status = EXCLUDED.status, tasks_assigned_count = EXCLUDED.tasks_assigned_count;

INSERT INTO personnel (id, created_at, email, name, tasks_assigned_count, role, status, department) VALUES ('loL5uL4o7BnDUw5tjHms', '2026-04-27T12:30:10.520Z', 'bob.r@entreprise.com', 'Bob Richards', 12, 'Directeur Logistique', 'active', 'Opérations') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, email = EXCLUDED.email, name = EXCLUDED.name, tasks_assigned_count = EXCLUDED.tasks_assigned_count, role = EXCLUDED.role, status = EXCLUDED.status, department = EXCLUDED.department;

INSERT INTO personnel (id, first_name, status, tasks_assigned_count, created_at, last_name, department, company_id, name, phone, updated_at, notes, role, email) VALUES ('ousmailambangl1@gmail.com', 'Ousmaila', 'active', 0, '2026-05-19T07:21:12.742Z', 'Mbang', 'Général', '6hSJ36FBdYOdXdGzjySR', 'Ousmaila Mbang', '69999', '2026-05-19T07:21:12.742Z', '', 'Directeur', 'ousmailambangl1@gmail.com') ON CONFLICT (id) DO UPDATE SET first_name = EXCLUDED.first_name, status = EXCLUDED.status, tasks_assigned_count = EXCLUDED.tasks_assigned_count, created_at = EXCLUDED.created_at, last_name = EXCLUDED.last_name, department = EXCLUDED.department, company_id = EXCLUDED.company_id, name = EXCLUDED.name, phone = EXCLUDED.phone, updated_at = EXCLUDED.updated_at, notes = EXCLUDED.notes, role = EXCLUDED.role, email = EXCLUDED.email;

INSERT INTO personnel (id, name, company_id, department, last_name, created_at, status, first_name, tasks_assigned_count, email, role, notes, updated_at, phone) VALUES ('ulXfHCA3QvbrCb0c4oXm', '(Clone) KOLLI ABE  FLORENCE', '77KDhS2qYXrWrUaN35yD', 'Général', 'FLORENCE ', '2026-05-27T06:59:56.743Z', 'active', 'KOLLI ABE ', 0, 'yaoubaboubakary43@gmail.com', 'Directeur', '', '2026-05-06T13:24:23.054Z', '') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, company_id = EXCLUDED.company_id, department = EXCLUDED.department, last_name = EXCLUDED.last_name, created_at = EXCLUDED.created_at, status = EXCLUDED.status, first_name = EXCLUDED.first_name, tasks_assigned_count = EXCLUDED.tasks_assigned_count, email = EXCLUDED.email, role = EXCLUDED.role, notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at, phone = EXCLUDED.phone;

INSERT INTO personnel (id, company_id, name, last_name, department, created_at, first_name, status, tasks_assigned_count, email, role, notes, updated_at, phone) VALUES ('yaoubaboubakary43@gmail.com', 'T8FEwFdIPTqkepcYrMxK', 'BOUBAKARY  Yaouba', 'Yaouba ', 'Général', '2026-05-16T18:07:52.423Z', 'BOUBAKARY ', 'active', 0, 'yaoubaboubakary43@gmail.com', 'Directeur', '', '2026-05-27T06:56:41.881Z', '') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, name = EXCLUDED.name, last_name = EXCLUDED.last_name, department = EXCLUDED.department, created_at = EXCLUDED.created_at, first_name = EXCLUDED.first_name, status = EXCLUDED.status, tasks_assigned_count = EXCLUDED.tasks_assigned_count, email = EXCLUDED.email, role = EXCLUDED.role, notes = EXCLUDED.notes, updated_at = EXCLUDED.updated_at, phone = EXCLUDED.phone;
