-- Migration for order_history (Part 1)

INSERT INTO order_history (id, reason, author_role, comment, new_status, created_at, order_id, company_id, previous_status, author_name) VALUES ('0J4ilVnRJ24VzeiB0saA', 'ANNULATION', 'owner', 'Zone de livraison hors de notre portée', 'CANCELLED_BY_SELLER', '2026-06-18T10:25:22.951Z', 'GrxJtA8ojQjaZbIRwOa5', '77KDhS2qYXrWrUaN35yD', 'PENDING', 'Système') ON CONFLICT (id) DO UPDATE SET reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, previous_status = EXCLUDED.previous_status, author_name = EXCLUDED.author_name;

INSERT INTO order_history (id, author_role, reason, new_status, comment, company_id, created_at, order_id, previous_status, author_name) VALUES ('37xrSTfXTCa70BMMlLB7', 'owner', 'ANNULATION', 'CANCELLED_BY_SELLER', 'Client injoignable', 'T8FEwFdIPTqkepcYrMxK', '2026-06-15T11:14:39.370Z', '0FjpYfAL7XIKN1C7tonw', 'SHIPPED', 'Système') ON CONFLICT (id) DO UPDATE SET author_role = EXCLUDED.author_role, reason = EXCLUDED.reason, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status, author_name = EXCLUDED.author_name;

INSERT INTO order_history (id, company_id, order_id, created_at, author_name, previous_status, reason, author_role, new_status, comment) VALUES ('5OuVjAAQhFBRvqAsxmPV', '3XCUYDcYRkBTouVbHggE', 'qU4Z2Oui38GVkTsQ3nMq', '2026-06-18T10:24:30.639Z', 'Système', 'PENDING', 'ANNULATION', 'owner', 'CANCELLED_BY_SELLER', 'Client injoignable') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment;

INSERT INTO order_history (id, new_status, comment, reason, author_role, author_name, previous_status, company_id, order_id, created_at) VALUES ('6YOi7goZFm3LXQWODe1t', 'CANCELLED_BY_SELLER', 'Client injoignable', 'ANNULATION', 'owner', 'Système', 'CANCELLED_BY_CUSTOMER', '3XCUYDcYRkBTouVbHggE', 'XUMjT4rea5A6pjLttPBv', '2026-06-17T05:56:43.158Z') ON CONFLICT (id) DO UPDATE SET new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at;

INSERT INTO order_history (id, author_name, previous_status, company_id, order_id, created_at, new_status, comment, author_role, reason) VALUES ('9WU6sSC7emRlCLqucsu3', 'Système', 'SHIPPED', '77KDhS2qYXrWrUaN35yD', 'vReKeHTtgu4ZDH37EgBA', '2026-05-14T10:56:44.525Z', 'DELIVERY_FAILED', 'Client absent / Injoignable', 'owner', 'STATUS_UPDATE') ON CONFLICT (id) DO UPDATE SET author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, author_role = EXCLUDED.author_role, reason = EXCLUDED.reason;

INSERT INTO order_history (id, reason, author_role, new_status, comment, company_id, created_at, order_id, previous_status, author_name) VALUES ('Ccj9YBsrmJlbeWfoo54F', 'STATUS_UPDATE', 'owner', 'SHIPPED', 'Nous viendrons livrer a motoau carrefour ', '77KDhS2qYXrWrUaN35yD', '2026-05-14T10:55:14.527Z', 'vReKeHTtgu4ZDH37EgBA', 'PROCESSING', 'Système') ON CONFLICT (id) DO UPDATE SET reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status, author_name = EXCLUDED.author_name;

INSERT INTO order_history (id, reason, author_role, comment, new_status, order_id, created_at, company_id, author_name, previous_status) VALUES ('CuxJeiuCJeuR91jsZTNb', 'ANNULATION', 'owner', 'Rupture de stock inattendue', 'CANCELLED_BY_SELLER', 'WuLkynvbXKmqnWrD63Wh', '2026-06-05T09:32:45.662Z', '77KDhS2qYXrWrUaN35yD', 'Système', 'PENDING') ON CONFLICT (id) DO UPDATE SET reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, new_status = EXCLUDED.new_status, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status;

INSERT INTO order_history (id, comment, new_status, reason, author_role, previous_status, author_name, created_at, order_id, company_id) VALUES ('ETmGIaRtR4lxYr6HQXcQ', 'Rupture de stock inattendue', 'CANCELLED_BY_SELLER', 'ANNULATION', 'owner', 'PENDING', 'Système', '2026-06-17T05:56:02.177Z', 'Lnb07lXKcEIAR17Pd0Wo', '3XCUYDcYRkBTouVbHggE') ON CONFLICT (id) DO UPDATE SET comment = EXCLUDED.comment, new_status = EXCLUDED.new_status, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, previous_status = EXCLUDED.previous_status, author_name = EXCLUDED.author_name, created_at = EXCLUDED.created_at, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id;

INSERT INTO order_history (id, new_status, comment, reason, author_role, author_name, previous_status, company_id, order_id, created_at) VALUES ('FQ6kVjbiVM1pkmKxxJM8', 'PROCESSING', 'Prise en charge de la commande', 'STATUS_UPDATE', 'owner', 'Système', 'PENDING', '77KDhS2qYXrWrUaN35yD', 'MOnf6fkdkmRnn8yajZrZ', '2026-06-05T09:34:16.302Z') ON CONFLICT (id) DO UPDATE SET new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at;

INSERT INTO order_history (id, new_status, comment, author_role, reason, previous_status, author_name, company_id, created_at, order_id) VALUES ('FvX444lw7haLFWGvRHUA', 'CANCELLED_BY_SELLER', 'Rupture de stock inattendue', 'owner', 'ANNULATION', 'PROCESSING', 'Système', 'comp_nexus_master', '2026-06-11T21:26:51.315Z', 'RFl7ldwPxlag1tjWroin') ON CONFLICT (id) DO UPDATE SET new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, author_role = EXCLUDED.author_role, reason = EXCLUDED.reason, previous_status = EXCLUDED.previous_status, author_name = EXCLUDED.author_name, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, order_id = EXCLUDED.order_id;

INSERT INTO order_history (id, comment, new_status, author_role, reason, author_name, previous_status, order_id, created_at, company_id) VALUES ('NMhehjkAShCEaNALMLZy', 'Client injoignable', 'CANCELLED_BY_SELLER', 'owner', 'ANNULATION', 'Système', 'PENDING', '95NQHi2lb4q0Hv2EGWz5', '2026-06-05T09:33:29.272Z', '77KDhS2qYXrWrUaN35yD') ON CONFLICT (id) DO UPDATE SET comment = EXCLUDED.comment, new_status = EXCLUDED.new_status, author_role = EXCLUDED.author_role, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id;

INSERT INTO order_history (id, previous_status, author_name, company_id, created_at, order_id, new_status, comment, reason, author_role) VALUES ('OUDoz282KeuSTIPLuoz9', 'PENDING', 'Système', '77KDhS2qYXrWrUaN35yD', '2026-05-14T10:53:00.153Z', 'vReKeHTtgu4ZDH37EgBA', 'PROCESSING', 'Prise en charge de la commande', 'STATUS_UPDATE', 'owner') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, author_name = EXCLUDED.author_name, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, order_id = EXCLUDED.order_id, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role;

INSERT INTO order_history (id, company_id, order_id, created_at, author_name, previous_status, reason, author_role, new_status, comment) VALUES ('TnrQtziwvNYqwLe0Xoex', 'T8FEwFdIPTqkepcYrMxK', 'hNpdIuqaeIXkmeGhHxQQ', '2026-06-17T09:46:23.107Z', 'Système', 'PROCESSING', 'ANNULATION', 'owner', 'CANCELLED_BY_SELLER', 'Client injoignable') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment;

INSERT INTO order_history (id, company_id, order_id, created_at, author_name, previous_status, reason, author_role, new_status, comment) VALUES ('VPrAGEBIRiZpAf6CeaWE', 'T8FEwFdIPTqkepcYrMxK', 'HsMmcYITReOkdowEsssg', '2026-06-15T11:15:41.881Z', 'Système', 'PENDING', 'ANNULATION', 'owner', 'CANCELLED_BY_SELLER', 'Rupture de stock inattendue') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment;

INSERT INTO order_history (id, reason, author_role, new_status, comment, company_id, order_id, created_at, author_name, previous_status) VALUES ('VV2RRIqPZWNfxGpYGyxw', 'ANNULATION', 'owner', 'CANCELLED_BY_SELLER', 'Client injoignable', 'comp_nexus_master', 'jgxV5VCOH0pr4u1PMYKU', '2026-06-16T14:47:08.999Z', 'Système', 'PENDING') ON CONFLICT (id) DO UPDATE SET reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status;

INSERT INTO order_history (id, new_status, comment, reason, author_role, previous_status, author_name, company_id, created_at, order_id) VALUES ('dKMtaLZnnASRifdrzPKX', 'CANCELLED_BY_SELLER', 'Rupture de stock inattendue', 'ANNULATION', 'owner', 'PENDING', 'Système', 'T8FEwFdIPTqkepcYrMxK', '2026-06-05T09:35:22.812Z', 'ELW9XnMLmEIAlpTQk6pj') ON CONFLICT (id) DO UPDATE SET new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, previous_status = EXCLUDED.previous_status, author_name = EXCLUDED.author_name, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, order_id = EXCLUDED.order_id;

INSERT INTO order_history (id, comment, new_status, reason, author_role, author_name, previous_status, order_id, created_at, company_id) VALUES ('moPZR1SvUnBJajg0DCWI', 'Rupture de stock inattendue', 'CANCELLED_BY_SELLER', 'ANNULATION', 'owner', 'Système', 'PENDING', 'aRx0L8DmYSa7WYTOSP39', '2026-06-05T09:35:10.287Z', 'T8FEwFdIPTqkepcYrMxK') ON CONFLICT (id) DO UPDATE SET comment = EXCLUDED.comment, new_status = EXCLUDED.new_status, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id;

INSERT INTO order_history (id, author_name, previous_status, order_id, created_at, company_id, comment, new_status, author_role, reason) VALUES ('oFkuAXAdulcqN5mxA0B3', 'Système', 'PROCESSING', '0FjpYfAL7XIKN1C7tonw', '2026-06-05T09:37:28.944Z', 'T8FEwFdIPTqkepcYrMxK', 'Livraison standard', 'SHIPPED', 'owner', 'STATUS_UPDATE') ON CONFLICT (id) DO UPDATE SET author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, company_id = EXCLUDED.company_id, comment = EXCLUDED.comment, new_status = EXCLUDED.new_status, author_role = EXCLUDED.author_role, reason = EXCLUDED.reason;

INSERT INTO order_history (id, previous_status, author_name, company_id, created_at, order_id, new_status, comment, reason, author_role) VALUES ('qixsiOnSKffA8omfrEDd', 'DELIVERED', 'Système', '77KDhS2qYXrWrUaN35yD', '2026-05-18T08:13:17.369Z', '2NbDVwMOfxjSGXATpt9x', 'DELIVERED', 'Paiement validé - Bénéfice Net: 1260000 FCFA (Frais: 0)', 'PAIEMENT', 'owner') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, author_name = EXCLUDED.author_name, company_id = EXCLUDED.company_id, created_at = EXCLUDED.created_at, order_id = EXCLUDED.order_id, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role;

INSERT INTO order_history (id, company_id, order_id, created_at, author_name, previous_status, reason, author_role, new_status, comment) VALUES ('wyG4oAlNN1AyvZVDdQtD', 'T8FEwFdIPTqkepcYrMxK', '0FjpYfAL7XIKN1C7tonw', '2026-06-05T09:36:04.635Z', 'Système', 'PENDING', 'STATUS_UPDATE', 'owner', 'PROCESSING', 'Prise en charge de la commande') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, created_at = EXCLUDED.created_at, author_name = EXCLUDED.author_name, previous_status = EXCLUDED.previous_status, reason = EXCLUDED.reason, author_role = EXCLUDED.author_role, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment;
