-- Migration for stock_history (Part 1)

INSERT INTO stock_history (id, quantity, company_id, product_name, reason, new_stock, type, purchase_price, created_at, previous_stock, author_name, product_id) VALUES ('HsT5vJNy84mKdPRZKWV5', 1800, 'ZHU4XkMEWWBgwfapUYPY', 'Spécial vacances utiles jeunes ', 'Mise à jour inventaire', 2000, 'ENTREE', 0, '2026-06-13T14:38:25.049Z', 200, 'Admin', 'w9xRoMv1YojaDKFHu9ki') ON CONFLICT (id) DO UPDATE SET quantity = EXCLUDED.quantity, company_id = EXCLUDED.company_id, product_name = EXCLUDED.product_name, reason = EXCLUDED.reason, new_stock = EXCLUDED.new_stock, type = EXCLUDED.type, purchase_price = EXCLUDED.purchase_price, created_at = EXCLUDED.created_at, previous_stock = EXCLUDED.previous_stock, author_name = EXCLUDED.author_name, product_id = EXCLUDED.product_id;

INSERT INTO stock_history (id, product_name, company_id, quantity, product_id, author_name, created_at, previous_stock, purchase_price, type, new_stock, reason) VALUES ('RlxcesTviqkgUERVwESI', 'HP ELITE BOOK', 'T8FEwFdIPTqkepcYrMxK', 0, 'RpmtwpaUucdtsue2831g', 'Admin', '2026-06-17T10:40:03.266Z', 2, 0, 'SORTIE', 2, 'Mise à jour inventaire') ON CONFLICT (id) DO UPDATE SET product_name = EXCLUDED.product_name, company_id = EXCLUDED.company_id, quantity = EXCLUDED.quantity, product_id = EXCLUDED.product_id, author_name = EXCLUDED.author_name, created_at = EXCLUDED.created_at, previous_stock = EXCLUDED.previous_stock, purchase_price = EXCLUDED.purchase_price, type = EXCLUDED.type, new_stock = EXCLUDED.new_stock, reason = EXCLUDED.reason;

INSERT INTO stock_history (id, author_name, product_id, created_at, previous_stock, purchase_price, type, new_stock, reason, product_name, company_id, quantity) VALUES ('TdTj5MGnu63AC3Lpufj4', 'Admin', 'r46LfEn9KSKBKFv52EDL', '2026-06-03T11:44:54.375Z', 15, 0, 'SORTIE', 15, 'Mise à jour inventaire', 'Ordinateur Portable Pro', 'T8FEwFdIPTqkepcYrMxK', 0) ON CONFLICT (id) DO UPDATE SET author_name = EXCLUDED.author_name, product_id = EXCLUDED.product_id, created_at = EXCLUDED.created_at, previous_stock = EXCLUDED.previous_stock, purchase_price = EXCLUDED.purchase_price, type = EXCLUDED.type, new_stock = EXCLUDED.new_stock, reason = EXCLUDED.reason, product_name = EXCLUDED.product_name, company_id = EXCLUDED.company_id, quantity = EXCLUDED.quantity;

INSERT INTO stock_history (id, company_id, quantity, product_name, previous_stock, created_at, type, purchase_price, reason, new_stock, author_name, product_id) VALUES ('kmPCXpbLbebtVVRAAVAP', 'T8FEwFdIPTqkepcYrMxK', 0, 'Ordinateur Portable Pro', 15, '2026-06-03T11:45:21.348Z', 'SORTIE', 0, 'Mise à jour inventaire', 15, 'Admin', 'r46LfEn9KSKBKFv52EDL') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, quantity = EXCLUDED.quantity, product_name = EXCLUDED.product_name, previous_stock = EXCLUDED.previous_stock, created_at = EXCLUDED.created_at, type = EXCLUDED.type, purchase_price = EXCLUDED.purchase_price, reason = EXCLUDED.reason, new_stock = EXCLUDED.new_stock, author_name = EXCLUDED.author_name, product_id = EXCLUDED.product_id;

INSERT INTO stock_history (id, previous_stock, created_at, purchase_price, type, reason, new_stock, author_name, product_id, company_id, quantity, product_name) VALUES ('qLqRGuUbgibY0UAdhRZF', 2, '2026-06-17T10:40:02.769Z', 0, 'SORTIE', 'Mise à jour inventaire', 2, 'Admin', 'RpmtwpaUucdtsue2831g', 'T8FEwFdIPTqkepcYrMxK', 0, 'HP ELITE BOOK') ON CONFLICT (id) DO UPDATE SET previous_stock = EXCLUDED.previous_stock, created_at = EXCLUDED.created_at, purchase_price = EXCLUDED.purchase_price, type = EXCLUDED.type, reason = EXCLUDED.reason, new_stock = EXCLUDED.new_stock, author_name = EXCLUDED.author_name, product_id = EXCLUDED.product_id, company_id = EXCLUDED.company_id, quantity = EXCLUDED.quantity, product_name = EXCLUDED.product_name;

INSERT INTO stock_history (id, product_name, quantity, company_id, product_id, author_name, reason, new_stock, type, purchase_price, created_at, previous_stock) VALUES ('vCxfRNiNaNMis8T9y0vE', 'HP ELITE BOOK', 0, 'T8FEwFdIPTqkepcYrMxK', 'RpmtwpaUucdtsue2831g', 'Admin', 'Mise à jour inventaire', 2, 'SORTIE', 0, '2026-06-17T10:40:01.890Z', 2) ON CONFLICT (id) DO UPDATE SET product_name = EXCLUDED.product_name, quantity = EXCLUDED.quantity, company_id = EXCLUDED.company_id, product_id = EXCLUDED.product_id, author_name = EXCLUDED.author_name, reason = EXCLUDED.reason, new_stock = EXCLUDED.new_stock, type = EXCLUDED.type, purchase_price = EXCLUDED.purchase_price, created_at = EXCLUDED.created_at, previous_stock = EXCLUDED.previous_stock;

INSERT INTO stock_history (id, product_name, company_id, quantity, product_id, author_name, created_at, previous_stock, type, purchase_price, reason, new_stock) VALUES ('xnCrIqIH5xWMni3R51C7', ' Fer à repasser RAF ELECTRIC STEAM IRON', '3XCUYDcYRkBTouVbHggE', 0, 'ptCvLJGCU5UYwiGfacsq', 'Admin', '2026-06-19T06:28:41.354Z', 10, 'SORTIE', 0, 'Mise à jour inventaire', 10) ON CONFLICT (id) DO UPDATE SET product_name = EXCLUDED.product_name, company_id = EXCLUDED.company_id, quantity = EXCLUDED.quantity, product_id = EXCLUDED.product_id, author_name = EXCLUDED.author_name, created_at = EXCLUDED.created_at, previous_stock = EXCLUDED.previous_stock, type = EXCLUDED.type, purchase_price = EXCLUDED.purchase_price, reason = EXCLUDED.reason, new_stock = EXCLUDED.new_stock;
