-- Migration for clients (Part 1)

INSERT INTO clients (id, phone, name, sales_total, email, loyalty_points, created_at) VALUES ('22VpzrHvmb4FMwuRgTrK', '01 23 45 67 89', 'Entreprise Alpha', 15400, 'contact@alpha.com', 120, '2026-04-27T12:30:04.837Z') ON CONFLICT (id) DO UPDATE SET phone = EXCLUDED.phone, name = EXCLUDED.name, sales_total = EXCLUDED.sales_total, email = EXCLUDED.email, loyalty_points = EXCLUDED.loyalty_points, created_at = EXCLUDED.created_at;

INSERT INTO clients (id, address, name, email, company_id, phone, sales_total, loyalty_points, created_at) VALUES ('3A62iy8EamlMGoIa1nZj', 'Maroua', 'Cyrille feuhku mba', 'feuhkumbac@gmail.com', '77KDhS2qYXrWrUaN35yD', '694826986', 0, 0, '2026-05-08T09:58:54.187Z') ON CONFLICT (id) DO UPDATE SET address = EXCLUDED.address, name = EXCLUDED.name, email = EXCLUDED.email, company_id = EXCLUDED.company_id, phone = EXCLUDED.phone, sales_total = EXCLUDED.sales_total, loyalty_points = EXCLUDED.loyalty_points, created_at = EXCLUDED.created_at;

INSERT INTO clients (id, name, email, company_id, address, sales_total, loyalty_points, updated_at, created_at, phone) VALUES ('L7zvj3iYVAZssKpafrCe', 'Raphael ', 'raphaeldoba1@gmail.com', '77KDhS2qYXrWrUaN35yD', 'Maroua', 0, 0, '2026-05-08T14:39:35.422Z', '2026-05-08T09:43:53.611Z', '656326890') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, company_id = EXCLUDED.company_id, address = EXCLUDED.address, sales_total = EXCLUDED.sales_total, loyalty_points = EXCLUDED.loyalty_points, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, phone = EXCLUDED.phone;

INSERT INTO clients (id, sales_total, email, name, created_at, loyalty_points, phone) VALUES ('SXTTwj1ss0lFU2oWFgyr', 3200, 'jean.martin@gmail.com', 'Jean Martin', '2026-04-27T12:30:05.516Z', 45, '06 12 34 56 78') ON CONFLICT (id) DO UPDATE SET sales_total = EXCLUDED.sales_total, email = EXCLUDED.email, name = EXCLUDED.name, created_at = EXCLUDED.created_at, loyalty_points = EXCLUDED.loyalty_points, phone = EXCLUDED.phone;

INSERT INTO clients (id, sales_total, updated_at, created_at, loyalty_points, phone, email, name, company_id, address) VALUES ('UeCavY78ElTgHL2xA3WJ', 0, '2026-05-08T14:39:28.841Z', '2026-05-08T13:32:03.497Z', 0, '6570466603', 'doumaira52@gmail.com', 'DOUMARA', '77KDhS2qYXrWrUaN35yD', 'Maroua ') ON CONFLICT (id) DO UPDATE SET sales_total = EXCLUDED.sales_total, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, loyalty_points = EXCLUDED.loyalty_points, phone = EXCLUDED.phone, email = EXCLUDED.email, name = EXCLUDED.name, company_id = EXCLUDED.company_id, address = EXCLUDED.address;

INSERT INTO clients (id, created_at, updated_at, loyalty_points, sales_total, phone, company_id, email, name, address) VALUES ('alayeasna948@gmail.com', '2026-05-09T11:01:33.424Z', '2026-05-09T11:01:33.424Z', 0, 0, '', '77KDhS2qYXrWrUaN35yD', 'alayeasna948@gmail.com', 'Alaye asna ', 'Maroua') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, loyalty_points = EXCLUDED.loyalty_points, sales_total = EXCLUDED.sales_total, phone = EXCLUDED.phone, company_id = EXCLUDED.company_id, email = EXCLUDED.email, name = EXCLUDED.name, address = EXCLUDED.address;

INSERT INTO clients (id, company_id, email, name, address, updated_at, created_at, loyalty_points, sales_total, phone) VALUES ('bienvenudounia41@gmail.com', '77KDhS2qYXrWrUaN35yD', 'bienvenudounia41@gmail.com', 'BIENVENUE ', 'Maroua', '2026-05-09T08:35:54.099Z', '2026-05-09T08:13:19.519Z', 0, 0, '691879186') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, email = EXCLUDED.email, name = EXCLUDED.name, address = EXCLUDED.address, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, loyalty_points = EXCLUDED.loyalty_points, sales_total = EXCLUDED.sales_total, phone = EXCLUDED.phone;

INSERT INTO clients (id, phone, created_at, updated_at, loyalty_points, sales_total, address, company_id, email, name) VALUES ('lamisalberto@gmail.com', '696771132', '2026-05-10T10:31:10.047Z', '2026-05-10T10:31:10.047Z', 0, 0, 'Maroua', '77KDhS2qYXrWrUaN35yD', 'lamisalberto@gmail.com', 'Lamissia albert') ON CONFLICT (id) DO UPDATE SET phone = EXCLUDED.phone, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, loyalty_points = EXCLUDED.loyalty_points, sales_total = EXCLUDED.sales_total, address = EXCLUDED.address, company_id = EXCLUDED.company_id, email = EXCLUDED.email, name = EXCLUDED.name;
