-- Migration for notifications (Part 1)

INSERT INTO notifications (id, is_read, message, user_id, updated_at, created_at, type, date, title, company_id) VALUES ('6OA85eiQb4rQnRECXrWO', 1, 'Adamou a passé une commande de 10 500 FCFA. Paiement: Espèces.', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '2026-05-18T07:50:12.679Z', '2026-05-14T10:50:57.303Z', 'alert', '2026-05-14T10:50:57.303Z', 'Nouvelle Commande (Cash sur place)', '77KDhS2qYXrWrUaN35yD') ON CONFLICT (id) DO UPDATE SET is_read = EXCLUDED.is_read, message = EXCLUDED.message, user_id = EXCLUDED.user_id, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, type = EXCLUDED.type, date = EXCLUDED.date, title = EXCLUDED.title, company_id = EXCLUDED.company_id;

INSERT INTO notifications (id, message, is_read, type, updated_at, created_at, user_id, company_id, title, date) VALUES ('7X2MepDaqTlf4AIGMmup', 'Faurest a passé une commande de 13 000 FCFA. Paiement: Espèces.', 1, 'alert', '2026-06-17T08:01:42.036Z', '2026-06-16T17:06:04.169Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', '3XCUYDcYRkBTouVbHggE', 'Nouvelle Commande (Cash sur place)', '2026-06-16T17:06:04.169Z') ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, is_read = EXCLUDED.is_read, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, title = EXCLUDED.title, date = EXCLUDED.date;

INSERT INTO notifications (id, is_read, message, created_at, date, company_id, title, type, user_id) VALUES ('7eznEJtvnlZUXDBWRWRA', 0, 'FAUREST  a passé une commande de 650 FCFA. Paiement: Espèces.', '2026-06-05T09:29:13.268Z', '2026-06-05T09:29:13.268Z', '77KDhS2qYXrWrUaN35yD', 'Nouvelle Commande (Cash sur place)', 'alert', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63') ON CONFLICT (id) DO UPDATE SET is_read = EXCLUDED.is_read, message = EXCLUDED.message, created_at = EXCLUDED.created_at, date = EXCLUDED.date, company_id = EXCLUDED.company_id, title = EXCLUDED.title, type = EXCLUDED.type, user_id = EXCLUDED.user_id;

INSERT INTO notifications (id, message, is_read, type, created_at, updated_at, user_id, title, company_id, date) VALUES ('AS3idHaVx2gEGj322TyL', 'faurest a passé une commande de 10 000 FCFA. Paiement: Espèces.', 1, 'alert', '2026-06-15T12:28:46.962Z', '2026-06-16T13:57:21.473Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'Nouvelle Commande (Cash sur place)', 'comp_nexus_master', '2026-06-15T12:28:46.962Z') ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, is_read = EXCLUDED.is_read, type = EXCLUDED.type, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, user_id = EXCLUDED.user_id, title = EXCLUDED.title, company_id = EXCLUDED.company_id, date = EXCLUDED.date;

INSERT INTO notifications (id, company_id, title, date, user_id, type, updated_at, created_at, message, is_read) VALUES ('DE04FhKfEG2daOrtQ6Ze', '77KDhS2qYXrWrUaN35yD', 'Nouvelle Commande (Cash sur place)', '2026-05-12T11:19:28.981Z', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', 'alert', '2026-05-18T07:50:13.434Z', '2026-05-12T11:19:28.981Z', 'Faurest  a passé une commande de 1 260 500 FCFA. Paiement: Espèces.', 1) ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, title = EXCLUDED.title, date = EXCLUDED.date, user_id = EXCLUDED.user_id, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, message = EXCLUDED.message, is_read = EXCLUDED.is_read;

INSERT INTO notifications (id, message, is_read, user_id, title, type, company_id, date, created_at) VALUES ('DMJt06Wo7iXxbUYVpJ0N', 'Faurest a passé une commande de 9 000 FCFA. Paiement: Espèces.', 0, 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', 'Nouvelle Commande (Cash sur place)', 'alert', '77KDhS2qYXrWrUaN35yD', '2026-06-12T12:39:22.429Z', '2026-06-12T12:39:22.429Z') ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, is_read = EXCLUDED.is_read, user_id = EXCLUDED.user_id, title = EXCLUDED.title, type = EXCLUDED.type, company_id = EXCLUDED.company_id, date = EXCLUDED.date, created_at = EXCLUDED.created_at;

INSERT INTO notifications (id, user_id, updated_at, created_at, type, is_read, message, date, company_id, title) VALUES ('E0brjhmwxTmmB0VrnKSz', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '2026-05-07T09:24:18.730Z', '2026-05-06T17:43:30.665Z', 'alert', 1, 'Le niveau de stock pour "RAM DE FORMAT" est faible (2 restants).', 1778089409412, '77KDhS2qYXrWrUaN35yD', 'Alerte de Stock Faible') ON CONFLICT (id) DO UPDATE SET user_id = EXCLUDED.user_id, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, type = EXCLUDED.type, is_read = EXCLUDED.is_read, message = EXCLUDED.message, date = EXCLUDED.date, company_id = EXCLUDED.company_id, title = EXCLUDED.title;

INSERT INTO notifications (id, user_id, company_id, type, title, date, created_at, message, is_read) VALUES ('ETa4z1UMt1m86F6FK0TJ', '5KwQgwL8XrIJkokLit39', '77KDhS2qYXrWrUaN35yD', 'general', 'Nouveau message direct', 1778141450663, '2026-05-07T08:10:51.763Z', 'Félicité Danga vous a envoyé un message.', 0) ON CONFLICT (id) DO UPDATE SET user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, type = EXCLUDED.type, title = EXCLUDED.title, date = EXCLUDED.date, created_at = EXCLUDED.created_at, message = EXCLUDED.message, is_read = EXCLUDED.is_read;

INSERT INTO notifications (id, title, company_id, date, user_id, type, updated_at, created_at, message, is_read) VALUES ('EhwHrJ5lhg7X1puqutBu', 'Nouvelle Commande (Cash sur place)', '3XCUYDcYRkBTouVbHggE', '2026-06-16T17:09:09.034Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'alert', '2026-06-17T08:00:46.232Z', '2026-06-16T17:09:09.034Z', 'Faurest a passé une commande de 1 500 FCFA. Paiement: Espèces.', 1) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, company_id = EXCLUDED.company_id, date = EXCLUDED.date, user_id = EXCLUDED.user_id, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, message = EXCLUDED.message, is_read = EXCLUDED.is_read;

INSERT INTO notifications (id, title, company_id, date, message, is_read, user_id, type, updated_at, created_at) VALUES ('FSUxiySpUxXVh2E5op8p', 'URGENT: Nouvelle Commande Marketplace Payée !', '77KDhS2qYXrWrUaN35yD', '2026-05-11T21:38:20.555Z', 'Le bolc a passé une commande de 10 650 FCFA et a payé par ORANGE.', 1, 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', 'alert', '2026-05-18T07:51:31.304Z', '2026-05-11T21:38:20.555Z') ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, company_id = EXCLUDED.company_id, date = EXCLUDED.date, message = EXCLUDED.message, is_read = EXCLUDED.is_read, user_id = EXCLUDED.user_id, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at;

INSERT INTO notifications (id, company_id, title, date, message, is_read, type, created_at, updated_at, user_id) VALUES ('PKEQ9Dg39sVelWrpphGx', 'comp_nexus_master', 'Commande Marketplace Payée !', '2026-05-11T21:56:54.398Z', 'Lord a passé une commande de 1 250 000 FCFA. Paiement: UNKNOWN.', 1, 'alert', '2026-05-11T21:56:54.398Z', '2026-05-12T12:14:06.872Z', '1xW5bszECGO04Xv4zRWMqclvQmL2') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, title = EXCLUDED.title, date = EXCLUDED.date, message = EXCLUDED.message, is_read = EXCLUDED.is_read, type = EXCLUDED.type, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, user_id = EXCLUDED.user_id;

INSERT INTO notifications (id, date, title, company_id, user_id, created_at, updated_at, type, is_read, message) VALUES ('RoTcjLrt4aTfJeQ5Dlwu', '2026-06-15T12:28:48.086Z', 'Nouvelle Commande (Cash sur place)', 'ZHU4XkMEWWBgwfapUYPY', '1xW5bszECGO04Xv4zRWMqclvQmL2', '2026-06-15T12:28:48.086Z', '2026-06-15T12:32:28.635Z', 'alert', 1, 'faurest a passé une commande de 15 000 FCFA. Paiement: Espèces.') ON CONFLICT (id) DO UPDATE SET date = EXCLUDED.date, title = EXCLUDED.title, company_id = EXCLUDED.company_id, user_id = EXCLUDED.user_id, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, type = EXCLUDED.type, is_read = EXCLUDED.is_read, message = EXCLUDED.message;

INSERT INTO notifications (id, user_id, updated_at, created_at, type, is_read, message, date, title, company_id) VALUES ('TbrkshTrQMP8bM9ZknlA', '1xW5bszECGO04Xv4zRWMqclvQmL2', '2026-06-18T10:24:10.744Z', '2026-06-17T11:03:26.258Z', 'alert', 1, 'Pro a passé une commande de 2 500 FCFA. Paiement: Espèces.', '2026-06-17T11:03:26.258Z', 'Nouvelle Commande (Cash sur place)', '3XCUYDcYRkBTouVbHggE') ON CONFLICT (id) DO UPDATE SET user_id = EXCLUDED.user_id, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, type = EXCLUDED.type, is_read = EXCLUDED.is_read, message = EXCLUDED.message, date = EXCLUDED.date, title = EXCLUDED.title, company_id = EXCLUDED.company_id;

INSERT INTO notifications (id, type, updated_at, created_at, user_id, message, is_read, company_id, title, date) VALUES ('Z7dYwSLy6x4DhDCjE8QU', 'alert', '2026-06-22T14:37:42.472Z', '2026-06-22T14:37:01.567Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'Faurest a passé une commande de 10 000 FCFA. Paiement: Espèces.', 1, 'comp_nexus_master', 'Nouvelle Commande (Cash sur place)', '2026-06-22T14:37:01.567Z') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, message = EXCLUDED.message, is_read = EXCLUDED.is_read, company_id = EXCLUDED.company_id, title = EXCLUDED.title, date = EXCLUDED.date;

INSERT INTO notifications (id, company_id, title, date, user_id, type, updated_at, created_at, message, is_read) VALUES ('jNgaIAObN1C9TknkFUZo', '77KDhS2qYXrWrUaN35yD', 'Alerte de Stock Faible', 1778089439962, 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', 'alert', '2026-05-07T09:24:06.633Z', '2026-05-06T17:44:01.234Z', 'Le niveau de stock pour "RAM DE FORMAT" est faible (2 restants).', 1) ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, title = EXCLUDED.title, date = EXCLUDED.date, user_id = EXCLUDED.user_id, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, message = EXCLUDED.message, is_read = EXCLUDED.is_read;

INSERT INTO notifications (id, is_read, message, created_at, updated_at, type, user_id, date, title, company_id) VALUES ('l2PaJ5HBUjtvlgfIC1uA', 1, 'Lord a passé une commande de 5 150 FCFA. Paiement: UNKNOWN.', '2026-05-11T21:56:51.997Z', '2026-05-18T07:50:54.116Z', 'alert', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '2026-05-11T21:56:51.997Z', 'Commande Marketplace Payée !', '77KDhS2qYXrWrUaN35yD') ON CONFLICT (id) DO UPDATE SET is_read = EXCLUDED.is_read, message = EXCLUDED.message, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, type = EXCLUDED.type, user_id = EXCLUDED.user_id, date = EXCLUDED.date, title = EXCLUDED.title, company_id = EXCLUDED.company_id;

INSERT INTO notifications (id, message, is_read, type, updated_at, created_at, user_id, company_id, title, date) VALUES ('lA2M1TOOy0PlUYgE69W8', 'Le niveau de stock pour "RAM DE FORMAT" est faible (5 restants).', 1, 'alert', '2026-05-07T09:25:15.277Z', '2026-05-06T17:36:36.757Z', 'K5gArXoEMGY4a1ymOIh7ZLSgVn63', '77KDhS2qYXrWrUaN35yD', 'Alerte de Stock Faible', 1778088995530) ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, is_read = EXCLUDED.is_read, type = EXCLUDED.type, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, user_id = EXCLUDED.user_id, company_id = EXCLUDED.company_id, title = EXCLUDED.title, date = EXCLUDED.date;

INSERT INTO notifications (id, date, title, company_id, is_read, message, user_id, updated_at, created_at, type) VALUES ('laI1N4EuSWId33Gwiacg', '2026-06-09T10:07:37.830Z', 'Nouveau message direct', 'ZHU4XkMEWWBgwfapUYPY', 1, 'Félicité Danga vous a envoyé un message.', '1xW5bszECGO04Xv4zRWMqclvQmL2', '2026-06-09T10:32:10.853Z', '2026-06-09T10:07:37.830Z', 'general') ON CONFLICT (id) DO UPDATE SET date = EXCLUDED.date, title = EXCLUDED.title, company_id = EXCLUDED.company_id, is_read = EXCLUDED.is_read, message = EXCLUDED.message, user_id = EXCLUDED.user_id, updated_at = EXCLUDED.updated_at, created_at = EXCLUDED.created_at, type = EXCLUDED.type;

INSERT INTO notifications (id, company_id, title, date, user_id, type, created_at, updated_at, message, is_read) VALUES ('vov82ci29HUNwC6KK7iV', '3XCUYDcYRkBTouVbHggE', 'Nouveau message direct', '2026-06-19T13:20:30.630Z', '1xW5bszECGO04Xv4zRWMqclvQmL2', 'general', '2026-06-19T13:20:30.630Z', '2026-06-22T08:20:30.056Z', 'Un collègue vous a envoyé un message.', 1) ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, title = EXCLUDED.title, date = EXCLUDED.date, user_id = EXCLUDED.user_id, type = EXCLUDED.type, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, message = EXCLUDED.message, is_read = EXCLUDED.is_read;
