-- Migration for order_history (Part 1)

INSERT INTO order_history (id, created_at, new_status, reason, author_name, author_role, comment, company_id, order_id, previous_status) VALUES ('0J4ilVnRJ24VzeiB0saA', '2026-06-18T10:25:22.951Z', 'CANCELLED_BY_SELLER', 'ANNULATION', 'Système', 'owner', 'Zone de livraison hors de notre portée', '77KDhS2qYXrWrUaN35yD', 'GrxJtA8ojQjaZbIRwOa5', 'PENDING') ON CONFLICT (id) DO UPDATE SET created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status;

INSERT INTO order_history (id, company_id, order_id, previous_status, reason, created_at, new_status, comment, author_role, author_name) VALUES ('37xrSTfXTCa70BMMlLB7', 'T8FEwFdIPTqkepcYrMxK', '0FjpYfAL7XIKN1C7tonw', 'SHIPPED', 'ANNULATION', '2026-06-15T11:14:39.370Z', 'CANCELLED_BY_SELLER', 'Client injoignable', 'owner', 'Système') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status, reason = EXCLUDED.reason, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, author_role = EXCLUDED.author_role, author_name = EXCLUDED.author_name;

INSERT INTO order_history (id, order_id, company_id, previous_status, created_at, new_status, reason, author_name, author_role, comment) VALUES ('5OuVjAAQhFBRvqAsxmPV', 'qU4Z2Oui38GVkTsQ3nMq', '3XCUYDcYRkBTouVbHggE', 'PENDING', '2026-06-18T10:24:30.639Z', 'CANCELLED_BY_SELLER', 'ANNULATION', 'Système', 'owner', 'Client injoignable') ON CONFLICT (id) DO UPDATE SET order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, previous_status = EXCLUDED.previous_status, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment;

INSERT INTO order_history (id, previous_status, company_id, order_id, author_role, comment, author_name, reason, new_status, created_at) VALUES ('6YOi7goZFm3LXQWODe1t', 'CANCELLED_BY_CUSTOMER', '3XCUYDcYRkBTouVbHggE', 'XUMjT4rea5A6pjLttPBv', 'owner', 'Client injoignable', 'Système', 'ANNULATION', 'CANCELLED_BY_SELLER', '2026-06-17T05:56:43.158Z') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, author_name = EXCLUDED.author_name, reason = EXCLUDED.reason, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at;

INSERT INTO order_history (id, company_id, order_id, previous_status, new_status, created_at, reason, author_name, comment, author_role) VALUES ('9WU6sSC7emRlCLqucsu3', '77KDhS2qYXrWrUaN35yD', 'vReKeHTtgu4ZDH37EgBA', 'SHIPPED', 'DELIVERY_FAILED', '2026-05-14T10:56:44.525Z', 'STATUS_UPDATE', 'Système', 'Client absent / Injoignable', 'owner') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, comment = EXCLUDED.comment, author_role = EXCLUDED.author_role;

INSERT INTO order_history (id, previous_status, company_id, order_id, author_name, author_role, comment, created_at, new_status, reason) VALUES ('Ccj9YBsrmJlbeWfoo54F', 'PROCESSING', '77KDhS2qYXrWrUaN35yD', 'vReKeHTtgu4ZDH37EgBA', 'Système', 'owner', 'Nous viendrons livrer a motoau carrefour ', '2026-05-14T10:55:14.527Z', 'SHIPPED', 'STATUS_UPDATE') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, reason = EXCLUDED.reason;

INSERT INTO order_history (id, previous_status, company_id, order_id, author_name, author_role, comment, new_status, created_at, reason) VALUES ('CuxJeiuCJeuR91jsZTNb', 'PENDING', '77KDhS2qYXrWrUaN35yD', 'WuLkynvbXKmqnWrD63Wh', 'Système', 'owner', 'Rupture de stock inattendue', 'CANCELLED_BY_SELLER', '2026-06-05T09:32:45.662Z', 'ANNULATION') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at, reason = EXCLUDED.reason;

INSERT INTO order_history (id, previous_status, order_id, company_id, author_name, author_role, comment, created_at, new_status, reason) VALUES ('ETmGIaRtR4lxYr6HQXcQ', 'PENDING', 'Lnb07lXKcEIAR17Pd0Wo', '3XCUYDcYRkBTouVbHggE', 'Système', 'owner', 'Rupture de stock inattendue', '2026-06-17T05:56:02.177Z', 'CANCELLED_BY_SELLER', 'ANNULATION') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, reason = EXCLUDED.reason;

INSERT INTO order_history (id, previous_status, order_id, company_id, author_role, comment, author_name, reason, new_status, created_at) VALUES ('FQ6kVjbiVM1pkmKxxJM8', 'PENDING', 'MOnf6fkdkmRnn8yajZrZ', '77KDhS2qYXrWrUaN35yD', 'owner', 'Prise en charge de la commande', 'Système', 'STATUS_UPDATE', 'PROCESSING', '2026-06-05T09:34:16.302Z') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, author_name = EXCLUDED.author_name, reason = EXCLUDED.reason, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at;

INSERT INTO order_history (id, previous_status, order_id, company_id, author_role, comment, author_name, reason, new_status, created_at) VALUES ('FvX444lw7haLFWGvRHUA', 'PROCESSING', 'RFl7ldwPxlag1tjWroin', 'comp_nexus_master', 'owner', 'Rupture de stock inattendue', 'Système', 'ANNULATION', 'CANCELLED_BY_SELLER', '2026-06-11T21:26:51.315Z') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, author_name = EXCLUDED.author_name, reason = EXCLUDED.reason, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at;

INSERT INTO order_history (id, company_id, order_id, previous_status, created_at, new_status, reason, author_name, author_role, comment) VALUES ('NMhehjkAShCEaNALMLZy', '77KDhS2qYXrWrUaN35yD', '95NQHi2lb4q0Hv2EGWz5', 'PENDING', '2026-06-05T09:33:29.272Z', 'CANCELLED_BY_SELLER', 'ANNULATION', 'Système', 'owner', 'Client injoignable') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment;

INSERT INTO order_history (id, company_id, order_id, previous_status, new_status, created_at, reason, author_name, author_role, comment) VALUES ('OUDoz282KeuSTIPLuoz9', '77KDhS2qYXrWrUaN35yD', 'vReKeHTtgu4ZDH37EgBA', 'PENDING', 'PROCESSING', '2026-05-14T10:53:00.153Z', 'STATUS_UPDATE', 'Système', 'owner', 'Prise en charge de la commande') ON CONFLICT (id) DO UPDATE SET company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment;

INSERT INTO order_history (id, new_status, created_at, reason, author_name, author_role, comment, order_id, company_id, previous_status) VALUES ('TnrQtziwvNYqwLe0Xoex', 'CANCELLED_BY_SELLER', '2026-06-17T09:46:23.107Z', 'ANNULATION', 'Système', 'owner', 'Client injoignable', 'hNpdIuqaeIXkmeGhHxQQ', 'T8FEwFdIPTqkepcYrMxK', 'PROCESSING') ON CONFLICT (id) DO UPDATE SET new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, previous_status = EXCLUDED.previous_status;

INSERT INTO order_history (id, previous_status, order_id, company_id, author_role, comment, author_name, reason, created_at, new_status) VALUES ('VPrAGEBIRiZpAf6CeaWE', 'PENDING', 'HsMmcYITReOkdowEsssg', 'T8FEwFdIPTqkepcYrMxK', 'owner', 'Rupture de stock inattendue', 'Système', 'ANNULATION', '2026-06-15T11:15:41.881Z', 'CANCELLED_BY_SELLER') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, author_name = EXCLUDED.author_name, reason = EXCLUDED.reason, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status;

INSERT INTO order_history (id, reason, new_status, created_at, author_role, comment, author_name, company_id, order_id, previous_status) VALUES ('VV2RRIqPZWNfxGpYGyxw', 'ANNULATION', 'CANCELLED_BY_SELLER', '2026-06-16T14:47:08.999Z', 'owner', 'Client injoignable', 'Système', 'comp_nexus_master', 'jgxV5VCOH0pr4u1PMYKU', 'PENDING') ON CONFLICT (id) DO UPDATE SET reason = EXCLUDED.reason, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, author_name = EXCLUDED.author_name, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status;

INSERT INTO order_history (id, previous_status, order_id, company_id, author_name, author_role, comment, new_status, created_at, reason) VALUES ('dKMtaLZnnASRifdrzPKX', 'PENDING', 'ELW9XnMLmEIAlpTQk6pj', 'T8FEwFdIPTqkepcYrMxK', 'Système', 'owner', 'Rupture de stock inattendue', 'CANCELLED_BY_SELLER', '2026-06-05T09:35:22.812Z', 'ANNULATION') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at, reason = EXCLUDED.reason;

INSERT INTO order_history (id, new_status, created_at, reason, author_name, author_role, comment, company_id, order_id, previous_status) VALUES ('moPZR1SvUnBJajg0DCWI', 'CANCELLED_BY_SELLER', '2026-06-05T09:35:10.287Z', 'ANNULATION', 'Système', 'owner', 'Rupture de stock inattendue', 'T8FEwFdIPTqkepcYrMxK', 'aRx0L8DmYSa7WYTOSP39', 'PENDING') ON CONFLICT (id) DO UPDATE SET new_status = EXCLUDED.new_status, created_at = EXCLUDED.created_at, reason = EXCLUDED.reason, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, previous_status = EXCLUDED.previous_status;

INSERT INTO order_history (id, reason, created_at, new_status, comment, author_role, author_name, order_id, company_id, previous_status) VALUES ('oFkuAXAdulcqN5mxA0B3', 'STATUS_UPDATE', '2026-06-05T09:37:28.944Z', 'SHIPPED', 'Livraison standard', 'owner', 'Système', '0FjpYfAL7XIKN1C7tonw', 'T8FEwFdIPTqkepcYrMxK', 'PROCESSING') ON CONFLICT (id) DO UPDATE SET reason = EXCLUDED.reason, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, comment = EXCLUDED.comment, author_role = EXCLUDED.author_role, author_name = EXCLUDED.author_name, order_id = EXCLUDED.order_id, company_id = EXCLUDED.company_id, previous_status = EXCLUDED.previous_status;

INSERT INTO order_history (id, previous_status, company_id, order_id, author_name, author_role, comment, created_at, new_status, reason) VALUES ('qixsiOnSKffA8omfrEDd', 'DELIVERED', '77KDhS2qYXrWrUaN35yD', '2NbDVwMOfxjSGXATpt9x', 'Système', 'owner', 'Paiement validé - Bénéfice Net: 1260000 FCFA (Frais: 0)', '2026-05-18T08:13:17.369Z', 'DELIVERED', 'PAIEMENT') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, author_name = EXCLUDED.author_name, author_role = EXCLUDED.author_role, comment = EXCLUDED.comment, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status, reason = EXCLUDED.reason;

INSERT INTO order_history (id, previous_status, company_id, order_id, comment, author_role, author_name, reason, created_at, new_status) VALUES ('wyG4oAlNN1AyvZVDdQtD', 'PENDING', 'T8FEwFdIPTqkepcYrMxK', '0FjpYfAL7XIKN1C7tonw', 'Prise en charge de la commande', 'owner', 'Système', 'STATUS_UPDATE', '2026-06-05T09:36:04.635Z', 'PROCESSING') ON CONFLICT (id) DO UPDATE SET previous_status = EXCLUDED.previous_status, company_id = EXCLUDED.company_id, order_id = EXCLUDED.order_id, comment = EXCLUDED.comment, author_role = EXCLUDED.author_role, author_name = EXCLUDED.author_name, reason = EXCLUDED.reason, created_at = EXCLUDED.created_at, new_status = EXCLUDED.new_status;
